"""init

Revision ID: 0a70a17823a9
Revises: 
Create Date: 2026-04-16 09:37:26.697768
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a70a17823a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('work_type', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('total_work_assigned', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_given', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bank_details', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_contact_number'), 'contractors', ['contact_number'], unique=True)
    op.create_index(op.f('ix_contractors_contractor_id'), 'contractors', ['contractor_id'], unique=True)
    op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_code', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_index(op.f('ix_owners_mobile'), 'owners', ['mobile'], unique=True)
    op.create_index(op.f('ix_owners_owner_code'), 'owners', ['owner_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('Admin', 'ProjectManager', 'SiteEngineer', 'Contractor', 'Accountant', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_table('ai_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('prediction', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_created_by_user_id'), 'ai_predictions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_ai_predictions_module_name'), 'ai_predictions', ['module_name'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.String(length=20), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ONGOING', 'COMPLETED', 'ON_HOLD', name='projectstatus'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='check_project_dates'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_business_id'), 'projects', ['business_id'], unique=True)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_project_name'), 'projects', ['project_name'], unique=False)
    op.create_table('boq_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('boq_group_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_latest', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('unit', sa.String(length=50), server_default='unit', nullable=False),
    sa.Column('unit_cost', sa.DECIMAL(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('actual_quantity', sa.DECIMAL(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('actual_cost', sa.DECIMAL(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('variance_cost', sa.DECIMAL(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='Active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_boq_group', 'boq_items', ['boq_group_id'], unique=False)
    op.create_index('idx_boq_latest', 'boq_items', ['is_latest'], unique=False)
    op.create_index('idx_boq_project', 'boq_items', ['project_id'], unique=False)
    op.create_index('idx_boq_status', 'boq_items', ['status'], unique=False)
    op.create_index(op.f('ix_boq_items_is_latest'), 'boq_items', ['is_latest'], unique=False)
    op.create_index(op.f('ix_boq_items_item_name'), 'boq_items', ['item_name'], unique=False)
    op.create_index(op.f('ix_boq_items_status'), 'boq_items', ['status'], unique=False)
    op.create_table('contractor_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_id', 'project_id', name='uq_contractor_project')
    )
    op.create_index(op.f('ix_contractor_projects_id'), 'contractor_projects', ['id'], unique=False)
    op.create_table('daily_site_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('site_location', sa.String(length=255), nullable=True),
    sa.Column('weather', sa.Enum('SUNNY', 'RAINY', 'CLOUDY', 'WINDY', name='weathertype'), nullable=True),
    sa.Column('work_done', sa.Text(), nullable=False),
    sa.Column('work_planned', sa.Text(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_labour', sa.Integer(), nullable=True),
    sa.Column('skilled_labour', sa.Integer(), nullable=True),
    sa.Column('unskilled_labour', sa.Integer(), nullable=True),
    sa.Column('machinery_used', sa.Text(), nullable=True),
    sa.Column('material_received', sa.Text(), nullable=True),
    sa.Column('material_used', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('safety_observations', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'report_date', name='uq_project_dsr_date')
    )
    op.create_index('idx_dsr_lat_lng', 'daily_site_reports', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_contractor_id'), 'daily_site_reports', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_created_by_id'), 'daily_site_reports', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_latitude'), 'daily_site_reports', ['latitude'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_longitude'), 'daily_site_reports', ['longitude'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_project_id'), 'daily_site_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_report_date'), 'daily_site_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_status'), 'daily_site_reports', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_user_id'), 'documents', ['uploaded_by_user_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('equipment_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=3), nullable=False),
    sa.Column('daily_cost', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_name'), 'equipment', ['equipment_name'], unique=False)
    op.create_index(op.f('ix_equipment_project_id'), 'equipment', ['project_id'], unique=False)
    op.create_index(op.f('ix_equipment_status'), 'equipment', ['status'], unique=False)
    op.create_table('final_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('final_area', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('approved_rate', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('extra_area', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('extra_rate', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('total_area', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_measurements_id'), 'final_measurements', ['id'], unique=False)
    op.create_index(op.f('ix_final_measurements_project_id'), 'final_measurements', ['project_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('linked_expense_ids', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('gst_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('tax_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_owner_id'), 'invoices', ['owner_id'], unique=False)
    op.create_index(op.f('ix_invoices_project_id'), 'invoices', ['project_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('MATERIAL', 'SAFETY', 'DELAY', name='issuecategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issuepriority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='issuestatus'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'title', name='uq_issue_project_title')
    )
    op.create_index('idx_issue_priority', 'issues', ['priority'], unique=False)
    op.create_index('idx_issue_project_priority', 'issues', ['project_id', 'priority'], unique=False)
    op.create_index('idx_issue_project_status', 'issues', ['project_id', 'status'], unique=False)
    op.create_index('idx_issue_reported_date', 'issues', ['reported_date'], unique=False)
    op.create_index('idx_issue_status', 'issues', ['status'], unique=False)
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_table('labour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_code', sa.String(length=50), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('labour_name', sa.String(length=255), nullable=False),
    sa.Column('skill_type', sa.Enum('SKILLED', 'UNSKILLED', name='skilltype'), nullable=False),
    sa.Column('daily_wage_rate', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='labourstatus'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'aadhaar_number', name='uq_project_aadhaar')
    )
    op.create_index(op.f('ix_labour_aadhaar_number'), 'labour', ['aadhaar_number'], unique=False)
    op.create_index(op.f('ix_labour_labour_name'), 'labour', ['labour_name'], unique=False)
    op.create_index(op.f('ix_labour_project_id'), 'labour', ['project_id'], unique=False)
    op.create_index(op.f('ix_labour_worker_code'), 'labour', ['worker_code'], unique=True)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), server_default='unit', nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('purchase_rate', sa.DECIMAL(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_purchased', sa.DECIMAL(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('quantity_used', sa.DECIMAL(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('remaining_stock', sa.DECIMAL(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('payment_given', sa.DECIMAL(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('payment_pending', sa.DECIMAL(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_material_category', 'materials', ['category'], unique=False)
    op.create_index('idx_material_project', 'materials', ['project_id'], unique=False)
    op.create_index(op.f('ix_materials_material_name'), 'materials', ['material_name'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'title', name='uq_milestone_project_title')
    )
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    op.create_index(op.f('ix_milestones_title'), 'milestones', ['title'], unique=False)
    op.create_table('owner_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_transactions_id'), 'owner_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_owner_transactions_owner_id'), 'owner_transactions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_owner_transactions_project_id'), 'owner_transactions', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_id_user_id')
    )
    op.create_index('idx_project_member_user', 'project_members', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'title', name='uq_task_project_title')
    )
    op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('work_order_number', sa.String(length=50), nullable=False),
    sa.Column('work_description', sa.String(length=255), nullable=False),
    sa.Column('total_quantity', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('completed_quantity', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_number')
    )
    op.create_index(op.f('ix_work_orders_contractor_id'), 'work_orders', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_project_id'), 'work_orders', ['project_id'], unique=False)
    op.create_table('boq_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('boq_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['boq_id'], ['boq_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_boq_audit_boq', 'boq_audit_logs', ['boq_id'], unique=False)
    op.create_index('idx_boq_audit_boq_created', 'boq_audit_logs', ['boq_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_boq_audit_logs_boq_id'), 'boq_audit_logs', ['boq_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_user_id'), 'comments', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.create_table('dsr_labour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dsr_id', sa.Integer(), nullable=False),
    sa.Column('labour_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF', name='attendancestatus'), nullable=False),
    sa.Column('working_hours', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('overtime_hours >= 0'),
    sa.CheckConstraint('working_hours >= 0'),
    sa.ForeignKeyConstraint(['dsr_id'], ['daily_site_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['labour_id'], ['labour.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dsr_id', 'labour_id', name='uq_dsr_labour')
    )
    op.create_index('idx_dsr_labour_dsr', 'dsr_labour', ['dsr_id'], unique=False)
    op.create_index('idx_dsr_labour_dsr_labour', 'dsr_labour', ['dsr_id', 'labour_id'], unique=False)
    op.create_index('idx_dsr_labour_labour', 'dsr_labour', ['labour_id'], unique=False)
    op.create_index(op.f('ix_dsr_labour_dsr_id'), 'dsr_labour', ['dsr_id'], unique=False)
    op.create_index(op.f('ix_dsr_labour_labour_id'), 'dsr_labour', ['labour_id'], unique=False)
    op.create_table('dsr_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dsr_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dsr_id'], ['daily_site_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsr_photos_dsr_id'), 'dsr_photos', ['dsr_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('boq_item_id', sa.Integer(), nullable=True),
    sa.Column('labour_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['labour_id'], ['labour.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_boq_item_id'), 'expenses', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_labour_id'), 'expenses', ['labour_id'], unique=False)
    op.create_index(op.f('ix_expenses_project_id'), 'expenses', ['project_id'], unique=False)
    op.create_table('labour_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labour_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF', name='attendancestatus'), nullable=False),
    sa.Column('in_time', sa.Time(), nullable=True),
    sa.Column('out_time', sa.Time(), nullable=True),
    sa.Column('working_hours', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('overtime_rate', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('task_description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['labour_id'], ['labour.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_labour_attendance_labour_date', 'labour_attendance', ['labour_id', 'attendance_date'], unique=False)
    op.create_index(op.f('ix_labour_attendance_attendance_date'), 'labour_attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_labour_attendance_labour_id'), 'labour_attendance', ['labour_id'], unique=False)
    op.create_index(op.f('ix_labour_attendance_project_id'), 'labour_attendance', ['project_id'], unique=False)
    op.create_table('labour_payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labour_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('total_working_hours', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_overtime_hours', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_wage', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('paid_amount', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('remaining_amount', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'PARTIAL', name='payrollstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['labour_id'], ['labour.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('quantity_used', sa.DECIMAL(precision=18, scale=3), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_usage_usage_date'), 'material_usage', ['usage_date'], unique=False)
    op.create_table('ra_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=False),
    sa.Column('work_description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=3), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('gross_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('deductions', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('net_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('gst_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ra_bills_bill_number'), 'ra_bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_ra_bills_contractor_id'), 'ra_bills', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_ra_bills_id'), 'ra_bills', ['id'], unique=False)
    op.create_index(op.f('ix_ra_bills_project_id'), 'ra_bills', ['project_id'], unique=False)
    op.create_table('task_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_progress_created_by_user_id'), 'task_progress', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_task_progress_task_id'), 'task_progress', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_progress_task_id'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_created_by_user_id'), table_name='task_progress')
    op.drop_table('task_progress')
    op.drop_index(op.f('ix_ra_bills_project_id'), table_name='ra_bills')
    op.drop_index(op.f('ix_ra_bills_id'), table_name='ra_bills')
    op.drop_index(op.f('ix_ra_bills_contractor_id'), table_name='ra_bills')
    op.drop_index(op.f('ix_ra_bills_bill_number'), table_name='ra_bills')
    op.drop_table('ra_bills')
    op.drop_index(op.f('ix_material_usage_usage_date'), table_name='material_usage')
    op.drop_table('material_usage')
    op.drop_table('labour_payroll')
    op.drop_index(op.f('ix_labour_attendance_project_id'), table_name='labour_attendance')
    op.drop_index(op.f('ix_labour_attendance_labour_id'), table_name='labour_attendance')
    op.drop_index(op.f('ix_labour_attendance_attendance_date'), table_name='labour_attendance')
    op.drop_index('idx_labour_attendance_labour_date', table_name='labour_attendance')
    op.drop_table('labour_attendance')
    op.drop_index(op.f('ix_expenses_project_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_labour_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_boq_item_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_dsr_photos_dsr_id'), table_name='dsr_photos')
    op.drop_table('dsr_photos')
    op.drop_index(op.f('ix_dsr_labour_labour_id'), table_name='dsr_labour')
    op.drop_index(op.f('ix_dsr_labour_dsr_id'), table_name='dsr_labour')
    op.drop_index('idx_dsr_labour_labour', table_name='dsr_labour')
    op.drop_index('idx_dsr_labour_dsr_labour', table_name='dsr_labour')
    op.drop_index('idx_dsr_labour_dsr', table_name='dsr_labour')
    op.drop_table('dsr_labour')
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_user_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_boq_audit_logs_boq_id'), table_name='boq_audit_logs')
    op.drop_index('idx_boq_audit_boq_created', table_name='boq_audit_logs')
    op.drop_index('idx_boq_audit_boq', table_name='boq_audit_logs')
    op.drop_table('boq_audit_logs')
    op.drop_index(op.f('ix_work_orders_project_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_contractor_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_project_member_user', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_owner_transactions_project_id'), table_name='owner_transactions')
    op.drop_index(op.f('ix_owner_transactions_owner_id'), table_name='owner_transactions')
    op.drop_index(op.f('ix_owner_transactions_id'), table_name='owner_transactions')
    op.drop_table('owner_transactions')
    op.drop_index(op.f('ix_milestones_title'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_materials_material_name'), table_name='materials')
    op.drop_index('idx_material_project', table_name='materials')
    op.drop_index('idx_material_category', table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_labour_worker_code'), table_name='labour')
    op.drop_index(op.f('ix_labour_project_id'), table_name='labour')
    op.drop_index(op.f('ix_labour_labour_name'), table_name='labour')
    op.drop_index(op.f('ix_labour_aadhaar_number'), table_name='labour')
    op.drop_table('labour')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_index('idx_issue_status', table_name='issues')
    op.drop_index('idx_issue_reported_date', table_name='issues')
    op.drop_index('idx_issue_project_status', table_name='issues')
    op.drop_index('idx_issue_project_priority', table_name='issues')
    op.drop_index('idx_issue_priority', table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_invoices_project_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_owner_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_final_measurements_project_id'), table_name='final_measurements')
    op.drop_index(op.f('ix_final_measurements_id'), table_name='final_measurements')
    op.drop_table('final_measurements')
    op.drop_index(op.f('ix_equipment_status'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_project_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_name'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_documents_uploaded_by_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_daily_site_reports_status'), table_name='daily_site_reports')
    op.drop_index(op.f('ix_daily_site_reports_report_date'), table_name='daily_site_reports')
    op.drop_index(op.f('ix_daily_site_reports_project_id'), table_name='daily_site_reports')
    op.drop_index(op.f('ix_daily_site_reports_longitude'), table_name='daily_site_reports')
    op.drop_index(op.f('ix_daily_site_reports_latitude'), table_name='daily_site_reports')
    op.drop_index(op.f('ix_daily_site_reports_created_by_id'), table_name='daily_site_reports')
    op.drop_index(op.f('ix_daily_site_reports_contractor_id'), table_name='daily_site_reports')
    op.drop_index('idx_dsr_lat_lng', table_name='daily_site_reports')
    op.drop_table('daily_site_reports')
    op.drop_index(op.f('ix_contractor_projects_id'), table_name='contractor_projects')
    op.drop_table('contractor_projects')
    op.drop_index(op.f('ix_boq_items_status'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_item_name'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_is_latest'), table_name='boq_items')
    op.drop_index('idx_boq_status', table_name='boq_items')
    op.drop_index('idx_boq_project', table_name='boq_items')
    op.drop_index('idx_boq_latest', table_name='boq_items')
    op.drop_index('idx_boq_group', table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_projects_project_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_business_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_ai_predictions_module_name'), table_name='ai_predictions')
    op.drop_index(op.f('ix_ai_predictions_created_by_user_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_owners_owner_code'), table_name='owners')
    op.drop_index(op.f('ix_owners_mobile'), table_name='owners')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_contractor_id'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_contact_number'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###

