"""Add UniqueConstraint to LabourPayroll

Revision ID: 0f4fbf155ee5
Revises: 3f8821e006b3
Create Date: 2026-08-07 15:11:25.972036
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4fbf155ee5'
down_revision = '3f8821e006b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_labour_payroll', 'labour_payroll', ['labour_id', 'project_id', 'month', 'year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_labour_payroll', 'labour_payroll', type_='unique')
    # ### end Alembic commands ###
