"""Add company_id to quotation_master

Revision ID: 1d3516138b0d
Revises: 060202e5d966
Create Date: 2026-08-25 23:46:28.037358
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add company_id to quotation_master

Revision ID: 1d3516138b0d
Revises: 060202e5d966
Create Date: 2026-08-25 23:46:28.037358
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3516138b0d'
down_revision = '060202e5d966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_master', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quotation_master_company_id'), 'quotation_master', ['company_id'], unique=False)
    op.create_foreign_key('fk_quotation_master_company_id', 'quotation_master', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    
    conn = op.get_bind()
    default_company_id = conn.execute(sa.text("SELECT id FROM companies ORDER BY id ASC LIMIT 1")).scalar()
    
    if default_company_id is not None:
        conn.execute(sa.text(f"UPDATE quotation_master SET company_id = {default_company_id} WHERE company_id IS NULL"))
        
        with op.batch_alter_table('quotation_master') as batch_op:
            batch_op.alter_column('company_id', server_default=sa.text(str(default_company_id)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_quotation_master_company_id', 'quotation_master', type_='foreignkey')
    op.drop_index(op.f('ix_quotation_master_company_id'), table_name='quotation_master')
    op.drop_column('quotation_master', 'company_id')
    # ### end Alembic commands ###
