"""client site eng accountant clean

Revision ID: 31314a7b795e
Revises: aaf8fb43b0e4
Create Date: 2026-04-27 12:34:33.207950
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31314a7b795e'
down_revision = 'aaf8fb43b0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE', 'EQUITY', name='accounttype'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_accounts_code', 'accounts', ['code'], unique=False)
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labour_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('credit', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journal_lines_account', 'journal_lines', ['account_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawing_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('drawing_name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('purchase_value', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('depreciation_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('current_value', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', name='message_status'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_created', 'messages', ['created_at'], unique=False)
    op.create_index('idx_message_project', 'messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('safety_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('violation_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('injury_details', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('responsible_person', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_safety_project', 'safety_incidents', ['project_id'], unique=False)
    op.create_table('site_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_project_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('financial_year', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tax_settings', sa.JSON(), nullable=True),
    sa.Column('invoice_format', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_audit_log_equipment_id'), 'equipment_audit_log', ['equipment_id'], unique=False)
    op.create_table('equipment_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equipment_maintenance_date', 'equipment_maintenance', ['equipment_id', 'maintenance_date'], unique=False)
    op.create_index(op.f('ix_equipment_maintenance_equipment_id'), 'equipment_maintenance', ['equipment_id'], unique=False)
    op.create_table('equipment_rental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rental_cost', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rental_cost >= 0', name='check_rental_cost_positive'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equipment_rental_dates', 'equipment_rental', ['equipment_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_equipment_rental_equipment_id'), 'equipment_rental', ['equipment_id'], unique=False)
    op.create_table('equipment_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('working_hours', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fuel_used', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fuel_used >= 0', name='check_usage_fuel_positive'),
    sa.CheckConstraint('working_hours >= 0', name='check_usage_hours_positive'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equipment_usage_date', 'equipment_usage', ['equipment_id', 'usage_date'], unique=False)
    op.create_index(op.f('ix_equipment_usage_equipment_id'), 'equipment_usage', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_usage_usage_date'), 'equipment_usage', ['usage_date'], unique=False)
    op.create_table('qc_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('dsr_id', sa.Integer(), nullable=True),
    sa.Column('inspection_type', sa.String(length=100), nullable=True),
    sa.Column('test_type', sa.String(length=100), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('standard_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('engineer_name', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('report_file_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dsr_id'], ['daily_site_reports.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qc_project', 'qc_records', ['project_id'], unique=False)
    op.create_table('site_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('activity_tag', sa.String(length=100), nullable=True),
    sa.Column('location_tag', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('linked_to', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_invoice_id'), 'transactions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_transactions_linked_to'), 'transactions', ['linked_to'], unique=False)
    op.create_index(op.f('ix_transactions_project_id'), 'transactions', ['project_id'], unique=False)
    # op.drop_table('documents')
    from sqlalchemy import inspect

    bind = op.get_bind()
    inspector = inspect(bind)

    if 'documents' in inspector.get_table_names():
        op.drop_table('documents')

    op.add_column('boq_items', sa.Column('activity_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'boq_items', 'activity_types', ['activity_type_id'], ['id'])
    op.add_column('equipment', sa.Column('equipment_code', sa.String(length=100), nullable=False))
    op.add_column('equipment', sa.Column('operator_name', sa.String(length=255), nullable=True))
    op.add_column('equipment', sa.Column('working_hours', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('equipment', sa.Column('fuel_used', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('equipment', sa.Column('condition', sa.Enum('GOOD', 'REPAIR', 'DAMAGED', name='equipmentcondition'), nullable=True))
    op.add_column('equipment', sa.Column('rental_cost', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('equipment', sa.Column('maintenance_date', sa.Date(), nullable=True))
    op.add_column('equipment', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('equipment', sa.Column('deleted_at', sa.Date(), nullable=True))
    op.add_column('equipment', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.alter_column('equipment', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('equipment', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('AVAILABLE', 'IN_PROJECT', 'IDLE', 'RENTED', 'MAINTENANCE', name='equipmentstatus'),
               existing_nullable=False)
    op.create_index('ix_equipment_code_unique_active', 'equipment', ['equipment_code'], unique=True)
    op.create_index(op.f('ix_equipment_condition'), 'equipment', ['condition'], unique=False)
    op.create_index(op.f('ix_equipment_equipment_code'), 'equipment', ['equipment_code'], unique=False)
    op.create_index(op.f('ix_equipment_is_deleted'), 'equipment', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_equipment_maintenance_date'), 'equipment', ['maintenance_date'], unique=False)
    op.create_index('ix_equipment_project_condition', 'equipment', ['project_id', 'condition'], unique=False)
    op.drop_constraint(op.f('equipment_ibfk_1'), 'equipment', type_='foreignkey')
    op.create_foreign_key(None, 'equipment', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_column('equipment', 'quantity')
    op.drop_column('equipment', 'total_cost')
    op.drop_column('equipment', 'category')
    op.drop_column('equipment', 'notes')
    op.drop_column('equipment', 'daily_cost')
    op.add_column('invoices', sa.Column('paid_amount', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('pending_amount', sa.DECIMAL(precision=18, scale=2), nullable=False))
    op.alter_column('invoices', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'PARTIAL', 'PAID', name='invoicestatus'),
               existing_nullable=True)
    op.add_column('materials', sa.Column('material_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_materials_material_code'), 'materials', ['material_code'], unique=True)
    op.add_column('purchase_orders', sa.Column('material_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchase_orders', 'materials', ['material_id'], ['id'])
    op.add_column('tasks', sa.Column('activity_type_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tasks_ibfk_1'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_user_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'activity_types', ['activity_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_ibfk_1'), 'tasks', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.drop_column('tasks', 'activity_type_id')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'material_id')
    op.drop_column('materials', 'material_code')
    op.create_index(op.f('uq_project_aadhaar'), 'labour', ['aadhaar_number'], unique=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.Enum('PENDING', 'PARTIAL', 'PAID', name='invoicestatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('invoices', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('invoices', 'pending_amount')
    op.drop_column('invoices', 'paid_amount')
    op.add_column('equipment', sa.Column('daily_cost', mysql.DECIMAL(precision=18, scale=2), nullable=False))
    op.add_column('equipment', sa.Column('notes', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('equipment', sa.Column('category', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('equipment', sa.Column('total_cost', mysql.DECIMAL(precision=18, scale=2), nullable=False))
    op.add_column('equipment', sa.Column('quantity', mysql.DECIMAL(precision=18, scale=3), nullable=False))
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.create_foreign_key(op.f('equipment_ibfk_1'), 'equipment', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('equipment', 'status',
               existing_type=sa.Enum('AVAILABLE', 'IN_PROJECT', 'IDLE', 'RENTED', 'MAINTENANCE', name='equipmentstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('equipment', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('equipment', 'deleted_by')
    op.drop_column('equipment', 'deleted_at')
    op.drop_column('equipment', 'is_deleted')
    op.drop_column('equipment', 'maintenance_date')
    op.drop_column('equipment', 'rental_cost')
    op.drop_column('equipment', 'condition')
    op.drop_column('equipment', 'fuel_used')
    op.drop_column('equipment', 'working_hours')
    op.drop_column('equipment', 'operator_name')
    op.drop_column('equipment', 'equipment_code')
    op.drop_constraint(None, 'boq_items', type_='foreignkey')
    op.drop_column('boq_items', 'activity_type_id')
    op.create_table('documents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('document_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('file_url', mysql.TEXT(), nullable=True),
    sa.Column('uploaded_by_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('documents_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('documents_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_documents_uploaded_by_user_id'), 'documents', ['uploaded_by_user_id'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.drop_table('transactions')
    op.drop_table('site_photos')
    op.drop_table('qc_records')
    op.drop_table('equipment_usage')
    op.drop_table('equipment_rental')
    op.drop_table('equipment_maintenance')
    op.drop_table('equipment_audit_log')
    op.drop_table('checklist_logs')
    op.drop_table('checklist_items')
    op.drop_table('user_settings')
    op.drop_table('site_requests')
    op.drop_table('safety_incidents')
    op.drop_table('messages')
    op.drop_table('fixed_assets')
    op.drop_table('drawing_documents')
    op.drop_table('checklists')
    op.drop_table('alerts')
    op.drop_table('journal_lines')
    op.drop_table('units')
    op.drop_table('material_master')
    op.drop_table('labour_types')
    op.drop_table('journal_entries')
    op.drop_table('activity_types')
    op.drop_table('accounts')
    # ### end Alembic commands ###

