"""udpate data

Revision ID: 380a43aa03a9
Revises: bf7597326a79
Create Date: 2026-04-02 12:33:36.891406
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380a43aa03a9'
down_revision = 'bf7597326a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('quantity_used', sa.DECIMAL(precision=18, scale=3), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_usage_usage_date'), 'material_usage', ['usage_date'], unique=False)
    op.add_column('expenses', sa.Column('boq_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_boq_item_id'), 'expenses', ['boq_item_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'boq_items', ['boq_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_boq_item_id'), table_name='expenses')
    op.drop_column('expenses', 'boq_item_id')
    op.drop_index(op.f('ix_material_usage_usage_date'), table_name='material_usage')
    op.drop_table('material_usage')
    # ### end Alembic commands ###

