"""initial unified architecture

Revision ID: 3bcfb82f7a21
Revises: b0090bc35520
Create Date: 2026-06-10 13:05:34.199823
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bcfb82f7a21'
down_revision = 'b0090bc35520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'action', name='uq_permission_module_action')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_table('project_ot_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.Enum('MULTIPLIER', 'FIXED_RATE', name='otpolicytype'), nullable=False),
    sa.Column('normal_day_multiplier', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('sunday_multiplier', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('holiday_multiplier', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fixed_ot_rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('message_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_delivery')
    )
    op.create_index('idx_delivery_message_user', 'message_deliveries', ['message_id', 'user_id'], unique=False)
    op.create_table('message_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'mentioned_user_id', name='uq_message_mention')
    )
    op.create_index('idx_message_mentions_message', 'message_mentions', ['message_id'], unique=False)
    op.create_index('idx_message_mentions_user', 'message_mentions', ['mentioned_user_id'], unique=False)
    op.create_table('user_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('in_time', sa.DateTime(), nullable=True),
    sa.Column('out_time', sa.DateTime(), nullable=True),
    sa.Column('check_in_image', sa.String(length=500), nullable=True),
    sa.Column('check_out_image', sa.String(length=500), nullable=True),
    sa.Column('working_hours', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('overtime_rate', sa.Float(), nullable=False),
    sa.Column('check_in_latitude', sa.Float(), nullable=True),
    sa.Column('check_in_longitude', sa.Float(), nullable=True),
    sa.Column('check_out_latitude', sa.Float(), nullable=True),
    sa.Column('check_out_longitude', sa.Float(), nullable=True),
    sa.Column('check_in_address', sa.String(length=255), nullable=True),
    sa.Column('check_out_address', sa.String(length=255), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('task_description', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('work_summary', sa.Text(), nullable=True),
    sa.Column('task_deadline_reason', sa.String(length=500), nullable=True),
    sa.Column('work_report_pdf', sa.String(length=500), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('is_outside_geofence', sa.Boolean(), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('is_early_departure', sa.Boolean(), nullable=False),
    sa.Column('early_minutes', sa.Integer(), nullable=False),
    sa.Column('work_location_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_attendance_project_date', 'user_attendance', ['project_id', 'attendance_date'], unique=False)
    op.create_index(op.f('ix_user_attendance_attendance_date'), 'user_attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_user_attendance_project_id'), 'user_attendance', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_attendance_user_id'), 'user_attendance', ['user_id'], unique=False)
    op.add_column('activity_types', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('activity_types',sa.Column('default_unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_activity_types_default_unit", "activity_types", "units", ["default_unit_id"], ["id"])
    op.add_column('chat_members', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.add_column('chat_members', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('chat_members', sa.Column('pinned_at', sa.DateTime(), nullable=True))
    op.add_column('chat_members', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index('idx_chatmember_chat_deleted', 'chat_members', ['chat_id', 'is_deleted'], unique=False)
    op.alter_column('chat_messages', 'message',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_index('idx_chat_pinned', 'chat_messages', ['chat_id', 'is_pinned'], unique=False)
    op.create_index('idx_fulltext_message', 'chat_messages', ['message'], unique=False, mysql_prefix='FULLTEXT')
    op.add_column('daily_site_reports', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_daily_site_reports_task_id'), 'daily_site_reports', ['task_id'], unique=False)
    op.create_foreign_key(None, 'daily_site_reports', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.add_column('dsr_labour', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dsr_labour_task_id'), 'dsr_labour', ['task_id'], unique=False)
    op.create_foreign_key(None, 'dsr_labour', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.add_column('final_measurements', sa.Column('task_id', sa.Integer(), nullable=True))
    op.add_column('final_measurements', sa.Column('boq_item_id', sa.Integer(), nullable=True))
    op.add_column('final_measurements', sa.Column('measured_qty', sa.DECIMAL(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
    op.add_column('final_measurements', sa.Column('certified_qty', sa.DECIMAL(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
    op.add_column('final_measurements', sa.Column('rejected_qty', sa.DECIMAL(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
    op.add_column('final_measurements', sa.Column('retention_amount', sa.DECIMAL(precision=18, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('final_measurements', sa.Column('status', sa.String(length=50), server_default='DRAFT', nullable=False))
    op.create_index(op.f('ix_final_measurements_boq_item_id'), 'final_measurements', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_final_measurements_task_id'), 'final_measurements', ['task_id'], unique=False)
    op.create_foreign_key(None, 'final_measurements', 'boq_items', ['boq_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'final_measurements', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.add_column('labour', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('labour', sa.Column('mobile_number', sa.String(length=15), nullable=True))
    op.add_column('labour', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('labour', sa.Column('profile_image', sa.String(length=500), nullable=True))
    op.add_column('labour', sa.Column('labour_type_id', sa.Integer(), nullable=True))
    op.add_column('labour', sa.Column('custom_daily_wage_rate', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('labour', sa.Column('custom_ot_rate_per_hour', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('labour',sa.Column('pan_number', sa.String(length=20), nullable=True))
    op.add_column('labour',sa.Column('address', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_labour_labour_type_id'), 'labour', ['labour_type_id'], unique=False)
    op.create_index(op.f('ix_labour_mobile_number'), 'labour', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_labour_user_id'), 'labour', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'labour', ['email'])
    op.create_foreign_key(None, 'labour', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'labour', 'labour_types', ['labour_type_id'], ['id'])
    op.alter_column(
        'labour',
        'daily_wage_rate',
        existing_type=sa.DECIMAL(precision=18, scale=2),
        nullable=True
    )

    op.alter_column(
        'labour',
        'skill_type',
        existing_type=mysql.ENUM('SKILLED', 'UNSKILLED'),
        nullable=True
    )
    # op.drop_column('labour', 'skill_type')
    # op.drop_column('labour', 'daily_wage_rate')
    op.add_column('labour_types', sa.Column('skill_category', sa.Enum('SKILLED', 'SEMI_SKILLED', 'UNSKILLED', name='skilltype'), nullable=False))
    op.add_column('labour_types', sa.Column('default_daily_wage', sa.DECIMAL(precision=18, scale=2), nullable=False))
    op.add_column('labour_types', sa.Column('default_working_hours', sa.Integer(), nullable=True))
    op.add_column('labour_types', sa.Column('default_ot_rate_per_hour', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('labour_types', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('material_master', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('material_master', sa.Column('specification', sa.String(length=255), nullable=True))
    op.add_column('material_master', sa.Column('hsn_code', sa.String(length=50), nullable=True))
    op.add_column('material_master', sa.Column('default_rate', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('material_master', sa.Column('minimum_stock_level', sa.Integer(), nullable=True))
    op.add_column('material_master', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('material_transactions', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_material_transactions_task_id'), 'material_transactions', ['task_id'], unique=False)
    op.create_foreign_key(None, 'material_transactions', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.add_column('material_usage', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_material_usage_task_id'), 'material_usage', ['task_id'], unique=False)
    op.create_foreign_key(None, 'material_usage', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('unique_material_per_project_supplier', 'materials', ['project_id', 'material_name', 'supplier_id'])
    op.add_column('message_attachments', sa.Column('uploaded_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message_attachments', 'users', ['uploaded_by'], ['id'])
    op.create_index('idx_message_read_user', 'message_reads', ['user_id'], unique=False)
    op.create_unique_constraint('uq_message_read', 'message_reads', ['message_id', 'user_id'])
    op.add_column('milestones', sa.Column('actual_start_date', sa.Date(), nullable=True))
    op.add_column('milestones', sa.Column('actual_end_date', sa.Date(), nullable=True))
    op.alter_column('owner_transactions', 'type',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('owner_transactions', 'reference_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_index('idx_owner_reference', 'owner_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('ix_owner_transactions_reference_type'), 'owner_transactions', ['reference_type'], unique=False)
    op.create_index(op.f('ix_owner_transactions_type'), 'owner_transactions', ['type'], unique=False)
    op.add_column('projects', sa.Column('shift_start_time', sa.Time(), nullable=True))
    op.add_column('projects', sa.Column('shift_end_time', sa.Time(), nullable=True))
    op.add_column('projects', sa.Column('grace_period_minutes', sa.Integer(), nullable=False))
    op.add_column(
        'projects',
        sa.Column('quotation_id', sa.Integer(), nullable=True)
    )

    op.add_column(
        'projects',
        sa.Column(
            'budget_amount',
            sa.DECIMAL(precision=15, scale=2),
            nullable=False,
            server_default='0.00'
        )
    )

    op.create_index(
        op.f('ix_projects_quotation_id'),
        'projects',
        ['quotation_id'],
        unique=True
    )

    op.create_foreign_key(
        'fk_projects_quotation_id',
        'projects',
        'quotation_master',
        ['quotation_id'],
        ['id'],
        ondelete='SET NULL'
    )
    op.add_column('expenses', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_expenses_source_type'), 'expenses', ['source_type'], unique=False)
    op.add_column('ra_bills', sa.Column('measurement_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ra_bills_measurement_id'), 'ra_bills', ['measurement_id'], unique=False)
    op.create_foreign_key(None, 'ra_bills', 'final_measurements', ['measurement_id'], ['id'], ondelete='SET NULL')
    op.add_column('safety_incidents', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_safety_incidents_task_id'), 'safety_incidents', ['task_id'], unique=False)
    op.create_foreign_key(None, 'safety_incidents', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.add_column('site_photos', sa.Column('dsr_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_site_photos_dsr_id'), 'site_photos', ['dsr_id'], unique=False)
    op.create_foreign_key(None, 'site_photos', 'daily_site_reports', ['dsr_id'], ['id'], ondelete='SET NULL')
    op.create_table(
        "task_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("assigned_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "user_id", name="uq_task_assignment"),
    )
    op.create_index(
        op.f("ix_task_assignments_task_id"),
        "task_assignments",
        ["task_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_task_assignments_user_id"),
        "task_assignments",
        ["user_id"],
        unique=False,
    )
    op.execute("""
        INSERT INTO task_assignments (task_id, user_id, assigned_at)
        SELECT id, assigned_user_id, NOW()
        FROM tasks
        WHERE assigned_user_id IS NOT NULL;
    """)
    op.add_column('tasks', sa.Column('milestone_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('actual_start_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('actual_end_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('audio_instruction_url', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('instruction_image_url', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('task_icon', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tasks_milestone_id'), 'tasks', ['milestone_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'milestones', ['milestone_id'], ['id'], ondelete='SET NULL')
    op.add_column('units', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_assignments_user_id"), table_name="task_assignments")
    op.drop_index(op.f("ix_task_assignments_task_id"), table_name="task_assignments")
    op.drop_table("task_assignments")
    op.drop_column('users', 'department')
    op.drop_column('units', 'is_active')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_milestone_id'), table_name='tasks')
    op.drop_column('tasks', 'task_icon')
    op.drop_column('tasks', 'instruction_image_url')
    op.drop_column('tasks', 'audio_instruction_url')
    op.drop_column('tasks', 'actual_end_date')
    op.drop_column('tasks', 'actual_start_date')
    op.drop_column('tasks', 'milestone_id')
    op.drop_constraint(None, 'site_photos', type_='foreignkey')
    op.drop_index(op.f('ix_site_photos_dsr_id'), table_name='site_photos')
    op.drop_column('site_photos', 'dsr_id')
    op.drop_constraint(None, 'safety_incidents', type_='foreignkey')
    op.drop_index(op.f('ix_safety_incidents_task_id'), table_name='safety_incidents')
    op.drop_column('safety_incidents', 'task_id')
    op.drop_constraint(None, 'ra_bills', type_='foreignkey')
    op.drop_index(op.f('ix_ra_bills_measurement_id'), table_name='ra_bills')
    op.drop_column('ra_bills', 'measurement_id')
    op.drop_constraint(
        'fk_projects_quotation_id',
        'projects',
        type_='foreignkey'
    )

    op.drop_index(
        op.f('ix_projects_quotation_id'),
        table_name='projects'
    )

    op.drop_column('projects', 'budget_amount')
    op.drop_column('projects', 'quotation_id')
    op.drop_column('projects', 'grace_period_minutes')
    op.drop_column('projects', 'shift_end_time')
    op.drop_column('projects', 'shift_start_time')
    op.drop_index(op.f('ix_owner_transactions_type'), table_name='owner_transactions')
    op.drop_index(op.f('ix_owner_transactions_reference_type'), table_name='owner_transactions')
    op.drop_index('idx_owner_reference', table_name='owner_transactions')
    op.alter_column('owner_transactions', 'reference_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('owner_transactions', 'type',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.drop_column('milestones', 'actual_end_date')
    op.drop_column('milestones', 'actual_start_date')
    op.drop_constraint('uq_message_read', 'message_reads', type_='unique')
    op.drop_index('idx_message_read_user', table_name='message_reads')
    op.drop_constraint(None, 'message_attachments', type_='foreignkey')
    op.drop_column('message_attachments', 'uploaded_by')
    op.drop_constraint('unique_material_per_project_supplier', 'materials', type_='unique')
    op.drop_constraint(None, 'material_usage', type_='foreignkey')
    op.drop_index(op.f('ix_material_usage_task_id'), table_name='material_usage')
    op.drop_column('material_usage', 'task_id')
    op.drop_constraint(None, 'material_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_material_transactions_task_id'), table_name='material_transactions')
    op.drop_column('material_transactions', 'task_id')
    op.drop_column('material_master', 'is_active')
    op.drop_column('material_master', 'minimum_stock_level')
    op.drop_column('material_master', 'default_rate')
    op.drop_column('material_master', 'hsn_code')
    op.drop_column('material_master', 'specification')
    op.drop_column('material_master', 'brand')
    op.drop_column('labour_types', 'is_active')
    op.drop_column('labour_types', 'default_ot_rate_per_hour')
    op.drop_column('labour_types', 'default_working_hours')
    op.drop_column('labour_types', 'default_daily_wage')
    op.drop_column('labour_types', 'skill_category')
    op.add_column('labour', sa.Column('daily_wage_rate', mysql.DECIMAL(precision=18, scale=2), nullable=False))
    op.add_column('labour', sa.Column('skill_type', mysql.ENUM('SKILLED', 'UNSKILLED'), nullable=False))
    op.drop_constraint(None, 'labour', type_='foreignkey')
    op.drop_constraint(None, 'labour', type_='foreignkey')
    op.drop_constraint(None, 'labour', type_='unique')
    op.drop_index(op.f('ix_labour_user_id'), table_name='labour')
    op.drop_index(op.f('ix_labour_mobile_number'), table_name='labour')
    op.drop_index(op.f('ix_labour_labour_type_id'), table_name='labour')
    op.drop_column('labour', 'address')
    op.drop_column('labour', 'pan_number')
    op.drop_column('labour', 'custom_ot_rate_per_hour')
    op.drop_column('labour', 'custom_daily_wage_rate')
    op.drop_column('labour', 'labour_type_id')
    op.drop_column('labour', 'profile_image')
    op.drop_column('labour', 'email')
    op.drop_column('labour', 'mobile_number')
    op.drop_column('labour', 'user_id')
    op.drop_constraint(None, 'final_measurements', type_='foreignkey')
    op.drop_constraint(None, 'final_measurements', type_='foreignkey')
    op.drop_index(op.f('ix_final_measurements_task_id'), table_name='final_measurements')
    op.drop_index(op.f('ix_final_measurements_boq_item_id'), table_name='final_measurements')
    op.drop_column('final_measurements', 'status')
    op.drop_column('final_measurements', 'retention_amount')
    op.drop_column('final_measurements', 'rejected_qty')
    op.drop_column('final_measurements', 'certified_qty')
    op.drop_column('final_measurements', 'measured_qty')
    op.drop_column('final_measurements', 'boq_item_id')
    op.drop_column('final_measurements', 'task_id')
    op.drop_constraint(None, 'dsr_labour', type_='foreignkey')
    op.drop_index(op.f('ix_dsr_labour_task_id'), table_name='dsr_labour')
    op.drop_column('dsr_labour', 'task_id')
    op.drop_constraint(None, 'daily_site_reports', type_='foreignkey')
    op.drop_index(op.f('ix_daily_site_reports_task_id'), table_name='daily_site_reports')
    op.drop_column('daily_site_reports', 'task_id')
    op.drop_index('idx_fulltext_message', table_name='chat_messages', mysql_prefix='FULLTEXT')
    op.drop_index('idx_chat_pinned', table_name='chat_messages')
    op.alter_column('chat_messages', 'message',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_index('idx_chatmember_chat_deleted', table_name='chat_members')
    op.drop_column('chat_members', 'deleted_at')
    op.drop_column('chat_members', 'pinned_at')
    op.drop_column('chat_members', 'is_deleted')
    op.drop_column('chat_members', 'is_pinned')
    op.drop_constraint("fk_activity_types_default_unit", "activity_types", type_="foreignkey")
    op.drop_column("activity_types", "default_unit_id")
    op.drop_column('activity_types', 'is_active')
    op.drop_index(op.f('ix_user_attendance_user_id'), table_name='user_attendance')
    op.drop_index(op.f('ix_user_attendance_project_id'), table_name='user_attendance')
    op.drop_index(op.f('ix_user_attendance_attendance_date'), table_name='user_attendance')
    op.drop_index('idx_user_attendance_project_date', table_name='user_attendance')
    op.drop_table('user_attendance')
    op.drop_index('idx_message_mentions_user', table_name='message_mentions')
    op.drop_index('idx_message_mentions_message', table_name='message_mentions')
    op.drop_table('message_mentions')
    op.drop_index('idx_delivery_message_user', table_name='message_deliveries')
    op.drop_table('message_deliveries')
    op.drop_table('project_ot_policy')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index(op.f('ix_expenses_source_type'), table_name='expenses')
    op.drop_column('expenses', 'source_type')
    op.drop_table('permissions')
    # ### end Alembic commands ###

