"""create document_management table

Revision ID: 3d3d64691d0f
Revises: 884c40cc5b68
Create Date: 2026-05-15 11:56:45.011770
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d3d64691d0f'
down_revision = '884c40cc5b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_management',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'UNDER_REVIEW', name='documentstatus'), nullable=False),
    sa.Column('is_folder', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['document_management.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_management_project_id'), 'document_management', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_management_title'), 'document_management', ['title'], unique=False)
    op.create_index(op.f('ix_document_management_uploaded_by_user_id'), 'document_management', ['uploaded_by_user_id'], unique=False)
    op.create_table('owner_payment_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('milestone_name', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_amount', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('reference_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_payment_schedules_id'), 'owner_payment_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_owner_payment_schedules_owner_id'), 'owner_payment_schedules', ['owner_id'], unique=False)
    op.create_index(op.f('ix_owner_payment_schedules_project_id'), 'owner_payment_schedules', ['project_id'], unique=False)
    op.add_column('activity_types', sa.Column('unique_code', sa.String(length=50), nullable=True))
    op.add_column('activity_types', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'activity_types', ['unique_code'])
    op.add_column('company_settings', sa.Column('instagram_handle', sa.String(length=255), nullable=True))
    op.add_column('company_settings', sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
    op.add_column('labour_types', sa.Column('unique_code', sa.String(length=50), nullable=True))
    op.add_column('labour_types', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'labour_types', ['unique_code'])
    op.add_column('material_master', sa.Column('unique_code', sa.String(length=50), nullable=True))
    op.add_column('material_master', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'material_master', ['unique_code'])
    op.add_column('owners', sa.Column('satisfaction_score', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('units', sa.Column('unique_code', sa.String(length=50), nullable=True))
    op.add_column('units', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'units', ['unique_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='unique')
    op.drop_column('units', 'category')
    op.drop_column('units', 'unique_code')
    op.drop_column('owners', 'satisfaction_score')
    op.drop_constraint(None, 'material_master', type_='unique')
    op.drop_column('material_master', 'category')
    op.drop_column('material_master', 'unique_code')
    op.drop_constraint(None, 'labour_types', type_='unique')
    op.drop_column('labour_types', 'category')
    op.drop_column('labour_types', 'unique_code')
    op.drop_column('company_settings', 'whatsapp_number')
    op.drop_column('company_settings', 'instagram_handle')
    op.drop_constraint(None, 'activity_types', type_='unique')
    op.drop_column('activity_types', 'category')
    op.drop_column('activity_types', 'unique_code')
    op.drop_index(op.f('ix_owner_payment_schedules_project_id'), table_name='owner_payment_schedules')
    op.drop_index(op.f('ix_owner_payment_schedules_owner_id'), table_name='owner_payment_schedules')
    op.drop_index(op.f('ix_owner_payment_schedules_id'), table_name='owner_payment_schedules')
    op.drop_table('owner_payment_schedules')
    op.drop_index(op.f('ix_document_management_uploaded_by_user_id'), table_name='document_management')
    op.drop_index(op.f('ix_document_management_title'), table_name='document_management')
    op.drop_index(op.f('ix_document_management_project_id'), table_name='document_management')
    op.drop_table('document_management')
    # ### end Alembic commands ###

