"""create document_management table

Revision ID: 3d3d64691d0f
Revises: 884c40cc5b68
Create Date: 2026-05-15 11:56:45.011770
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d3d64691d0f'
down_revision = '884c40cc5b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_management',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'UNDER_REVIEW', name='documentstatus'), nullable=False),
    sa.Column('is_folder', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['document_management.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_management_project_id'), 'document_management', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_management_title'), 'document_management', ['title'], unique=False)
    op.create_index(op.f('ix_document_management_uploaded_by_user_id'), 'document_management', ['uploaded_by_user_id'], unique=False)
    op.create_table('owner_payment_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('milestone_name', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_amount', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('reference_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_payment_schedules_id'), 'owner_payment_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_owner_payment_schedules_owner_id'), 'owner_payment_schedules', ['owner_id'], unique=False)
    op.create_index(op.f('ix_owner_payment_schedules_project_id'), 'owner_payment_schedules', ['project_id'], unique=False)
    op.add_column('activity_types', sa.Column('unique_code', sa.String(length=50), nullable=True))
    op.add_column('activity_types', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'activity_types', ['unique_code'])
    op.add_column('company_settings', sa.Column('instagram_handle', sa.String(length=255), nullable=True))
    op.add_column('company_settings', sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
    op.add_column('labour_types', sa.Column('unique_code', sa.String(length=50), nullable=True))
    op.add_column('labour_types', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'labour_types', ['unique_code'])
    op.add_column('material_master', sa.Column('unique_code', sa.String(length=50), nullable=True))
    op.add_column('material_master', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'material_master', ['unique_code'])
    op.add_column('owners', sa.Column('satisfaction_score', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('units', sa.Column('unique_code', sa.String(length=50), nullable=True))
    op.add_column('units', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'units', ['unique_code'])
    op.drop_index(
        op.f('unique_material_per_project_supplier'),
        table_name='materials'
    )
    op.create_table('activity_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['work_activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_history_activity', 'activity_history', ['activity_id'], unique=False)
    op.create_index('idx_activity_history_changed_by', 'activity_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_activity_history_activity_id'), 'activity_history', ['activity_id'], unique=False)
    op.alter_column('daily_progress_entries', 'activity_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('daily_progress_entries', 'entry_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('daily_progress_entries', 'today_progress',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               nullable=False)
    op.create_index(op.f('ix_daily_progress_entries_activity_id'), 'daily_progress_entries', ['activity_id'], unique=False)
    op.create_index(op.f('ix_daily_progress_entries_entry_date'), 'daily_progress_entries', ['entry_date'], unique=False)
    op.create_unique_constraint('uq_activity_entry_date', 'daily_progress_entries', ['activity_id', 'entry_date'])
    op.drop_constraint(op.f('daily_progress_entries_ibfk_1'), 'daily_progress_entries', type_='foreignkey')
    op.create_foreign_key(None, 'daily_progress_entries', 'work_activities', ['activity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'daily_progress_entries', 'users', ['created_by'], ['id'])
    op.create_index(op.f('ix_work_activities_engineer_id'), 'work_activities', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_work_activities_project_id'), 'work_activities', ['project_id'], unique=False)
    op.create_foreign_key(None, 'work_activities', 'users', ['engineer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'work_activities', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index( 'idx_users_is_deleted_id', 'users', ['is_deleted', 'id'], unique=False )
    # ### end Alembic commands ###


def downgrade():
    # =====================================================
    # Revert work_activities changes
    # =====================================================
    op.drop_index('idx_users_is_deleted_id',table_name='users')
    op.drop_constraint(None, 'work_activities', type_='foreignkey')
    op.drop_constraint(None, 'work_activities', type_='foreignkey')
    op.drop_index(op.f('ix_work_activities_project_id'), table_name='work_activities')
    op.drop_index(op.f('ix_work_activities_engineer_id'), table_name='work_activities')
    # =====================================================
    # Revert daily_progress_entries
    # =====================================================
    op.drop_constraint(None, 'daily_progress_entries', type_='foreignkey')
    op.drop_constraint(None, 'daily_progress_entries', type_='foreignkey')
    op.create_foreign_key(
        op.f('daily_progress_entries_ibfk_1'),
        'daily_progress_entries',
        'work_activities',
        ['activity_id'],
        ['id']
    )

    op.drop_constraint('uq_activity_entry_date', 'daily_progress_entries', type_='unique')
    op.drop_index(op.f('ix_daily_progress_entries_entry_date'), table_name='daily_progress_entries')
    op.drop_index(op.f('ix_daily_progress_entries_activity_id'), table_name='daily_progress_entries')

    op.alter_column(
        'daily_progress_entries',
        'today_progress',
        existing_type=mysql.DECIMAL(precision=18, scale=2),
        nullable=True
    )
    op.alter_column(
        'daily_progress_entries',
        'entry_date',
        existing_type=sa.DATE(),
        nullable=True
    )
    op.alter_column(
        'daily_progress_entries',
        'activity_id',
        existing_type=mysql.INTEGER(),
        nullable=True
    )

    # =====================================================
    # Drop activity_history
    # =====================================================
    op.drop_index(op.f('ix_activity_history_activity_id'), table_name='activity_history')
    op.drop_index('idx_activity_history_changed_by', table_name='activity_history')
    op.drop_index('idx_activity_history_activity', table_name='activity_history')
    op.drop_table('activity_history')

    # =====================================================
    # Restore unique_material_per_project_supplier
    # =====================================================
    op.create_index(
        op.f('unique_material_per_project_supplier'),
        'materials',
        ['project_id', 'material_name', 'supplier_id'],
        unique=True
    )

    # =====================================================
    # Revert added columns
    # =====================================================
    op.drop_constraint(None, 'units', type_='unique')
    op.drop_column('units', 'category')
    op.drop_column('units', 'unique_code')

    op.drop_column('owners', 'satisfaction_score')

    op.drop_constraint(None, 'material_master', type_='unique')
    op.drop_column('material_master', 'category')
    op.drop_column('material_master', 'unique_code')

    op.drop_constraint(None, 'labour_types', type_='unique')
    op.drop_column('labour_types', 'category')
    op.drop_column('labour_types', 'unique_code')

    op.drop_column('company_settings', 'whatsapp_number')
    op.drop_column('company_settings', 'instagram_handle')

    op.drop_constraint(None, 'activity_types', type_='unique')
    op.drop_column('activity_types', 'category')
    op.drop_column('activity_types', 'unique_code')

    # =====================================================
    # Drop owner_payment_schedules
    # =====================================================
    op.drop_index(op.f('ix_owner_payment_schedules_project_id'), table_name='owner_payment_schedules')
    op.drop_index(op.f('ix_owner_payment_schedules_owner_id'), table_name='owner_payment_schedules')
    op.drop_index(op.f('ix_owner_payment_schedules_id'), table_name='owner_payment_schedules')
    op.drop_table('owner_payment_schedules')

    # =====================================================
    # Drop document_management
    # =====================================================
    op.drop_index(op.f('ix_document_management_uploaded_by_user_id'), table_name='document_management')
    op.drop_index(op.f('ix_document_management_title'), table_name='document_management')
    op.drop_index(op.f('ix_document_management_project_id'), table_name='document_management')
    op.drop_table('document_management')