"""Add grn_number to vendor_bills

Revision ID: 3f8821e006b3
Revises: 1901a325b8fe
Create Date: 2026-08-06 11:59:12.771229
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8821e006b3'
down_revision = '1901a325b8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_bill_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['vendor_bill_id'], ['vendor_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_bill_items_vendor_bill_id'), 'vendor_bill_items', ['vendor_bill_id'], unique=False)
    op.add_column('vendor_bills', sa.Column('grn_number', sa.String(length=100), nullable=True))
    op.add_column('vendor_bills', sa.Column('gross_amount', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('vendor_bills', sa.Column('gst_percent', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('vendor_bills', sa.Column('gst_amount', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('vendor_bills', sa.Column('tds_percent', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('vendor_bills', sa.Column('tds_amount', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('vendor_bills', sa.Column('advance_paid', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('vendor_bills', sa.Column('vendor_invoice_url', sa.String(length=500), nullable=True))
    op.add_column('vendor_bills', sa.Column('po_copy_url', sa.String(length=500), nullable=True))
    op.add_column('vendor_bills', sa.Column('grn_copy_url', sa.String(length=500), nullable=True))
    op.add_column('vendor_bills', sa.Column('supporting_docs_url', sa.String(length=500), nullable=True))
    op.add_column('transactions', sa.Column('journal_entry_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_journal_entry_id'), 'transactions', ['journal_entry_id'], unique=False)
    op.create_foreign_key('fk_transactions_journal_entry_id', 'transactions', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_journal_entry_id', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_journal_entry_id'), table_name='transactions')
    op.drop_column('transactions', 'journal_entry_id')
    op.drop_column('vendor_bills', 'supporting_docs_url')
    op.drop_column('vendor_bills', 'grn_copy_url')
    op.drop_column('vendor_bills', 'po_copy_url')
    op.drop_column('vendor_bills', 'vendor_invoice_url')
    op.drop_column('vendor_bills', 'advance_paid')
    op.drop_column('vendor_bills', 'tds_amount')
    op.drop_column('vendor_bills', 'tds_percent')
    op.drop_column('vendor_bills', 'gst_amount')
    op.drop_column('vendor_bills', 'gst_percent')
    op.drop_column('vendor_bills', 'gross_amount')
    op.drop_column('vendor_bills', 'grn_number')
    op.drop_table('vendor_bill_items')
    # ### end Alembic commands ###

