"""add project location and classification fields

Revision ID: 3fd3ff1623ee
Revises: f8f25a2f7400
Create Date: 2026-05-28 20:15:03.829375
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd3ff1623ee'
down_revision = 'f8f25a2f7400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', 'ROAD', 'BRIDGE', 'INTERIOR', 'VILLA', 'APARTMENT', 'TOWNSHIP', 'RENOVATION', name='projecttype'), nullable=True))
    op.add_column('projects', sa.Column('location_type', sa.Enum('URBAN', 'RURAL', 'SEMI_URBAN', 'HIGHWAY', 'REMOTE', 'INDUSTRIAL_ZONE', name='locationtype'), nullable=True))
    op.add_column('projects', sa.Column('site_address', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'longitude')
    op.drop_column('projects', 'latitude')
    op.drop_column('projects', 'pincode')
    op.drop_column('projects', 'country')
    op.drop_column('projects', 'state')
    op.drop_column('projects', 'city')
    op.drop_column('projects', 'site_address')
    op.drop_column('projects', 'location_type')
    op.drop_column('projects', 'type')
    # ### end Alembic commands ###

