"""add labour type migration

Revision ID: 47a4121119b4
Revises: e3fc2b7d2646
Create Date: 2026-06-09 14:21:24.800738
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47a4121119b4'
down_revision = 'e3fc2b7d2646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'action', name='uq_permission_module_action')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_table('message_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_delivery')
    )
    op.create_index('idx_delivery_message_user', 'message_deliveries', ['message_id', 'user_id'], unique=False)
    op.create_table('message_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'mentioned_user_id', name='uq_message_mention')
    )
    op.create_index('idx_message_mentions_message', 'message_mentions', ['message_id'], unique=False)
    op.create_index('idx_message_mentions_user', 'message_mentions', ['mentioned_user_id'], unique=False)
    op.add_column('activity_types', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('chat_members', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.add_column('chat_members', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('chat_members', sa.Column('pinned_at', sa.DateTime(), nullable=True))
    op.add_column('chat_members', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index('idx_chatmember_chat_deleted', 'chat_members', ['chat_id', 'is_deleted'], unique=False)
    op.alter_column('chat_messages', 'message',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_index('idx_chat_pinned', 'chat_messages', ['chat_id', 'is_pinned'], unique=False)
    op.create_index('idx_fulltext_message', 'chat_messages', ['message'], unique=False, mysql_prefix='FULLTEXT')
    op.add_column('labour', sa.Column('labour_type_id', sa.Integer(), nullable=True))
    op.add_column('labour', sa.Column('custom_daily_wage_rate', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('labour', sa.Column('custom_ot_rate_per_hour', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.create_index(op.f('ix_labour_labour_type_id'), 'labour', ['labour_type_id'], unique=False)
    op.create_foreign_key(None, 'labour', 'labour_types', ['labour_type_id'], ['id'])
    # op.drop_column('labour', 'skill_type')
    # op.drop_column('labour', 'daily_wage_rate')
    op.add_column('labour_types', sa.Column('skill_category', sa.Enum('SKILLED', 'SEMI_SKILLED', 'UNSKILLED', name='skilltype'), nullable=False))
    op.add_column('labour_types', sa.Column('default_daily_wage', sa.DECIMAL(precision=18, scale=2), nullable=False))
    op.add_column('labour_types', sa.Column('default_working_hours', sa.Integer(), nullable=True))
    op.add_column('labour_types', sa.Column('default_ot_rate_per_hour', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('labour_types', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('material_master', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('material_master', sa.Column('specification', sa.String(length=255), nullable=True))
    op.add_column('material_master', sa.Column('hsn_code', sa.String(length=50), nullable=True))
    op.add_column('material_master', sa.Column('default_rate', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('material_master', sa.Column('minimum_stock_level', sa.Integer(), nullable=True))
    op.add_column('material_master', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('message_attachments', sa.Column('uploaded_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message_attachments', 'users', ['uploaded_by'], ['id'])
    op.create_index('idx_message_read_user', 'message_reads', ['user_id'], unique=False)
    op.create_unique_constraint('uq_message_read', 'message_reads', ['message_id', 'user_id'])
    op.add_column('units', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'is_active')
    op.drop_constraint('uq_message_read', 'message_reads', type_='unique')
    op.drop_index('idx_message_read_user', table_name='message_reads')
    op.drop_constraint(None, 'message_attachments', type_='foreignkey')
    op.drop_column('message_attachments', 'uploaded_by')
    op.drop_column('material_master', 'is_active')
    op.drop_column('material_master', 'minimum_stock_level')
    op.drop_column('material_master', 'default_rate')
    op.drop_column('material_master', 'hsn_code')
    op.drop_column('material_master', 'specification')
    op.drop_column('material_master', 'brand')
    op.drop_column('labour_types', 'is_active')
    op.drop_column('labour_types', 'default_ot_rate_per_hour')
    op.drop_column('labour_types', 'default_working_hours')
    op.drop_column('labour_types', 'default_daily_wage')
    op.drop_column('labour_types', 'skill_category')
    # op.add_column('labour', sa.Column('daily_wage_rate', mysql.DECIMAL(precision=18, scale=2), nullable=False))
    # op.add_column('labour', sa.Column('skill_type', mysql.ENUM('SKILLED', 'UNSKILLED'), nullable=False))
    op.drop_constraint(None, 'labour', type_='foreignkey')
    op.drop_index(op.f('ix_labour_labour_type_id'), table_name='labour')
    op.drop_column('labour', 'custom_ot_rate_per_hour')
    op.drop_column('labour', 'custom_daily_wage_rate')
    op.drop_column('labour', 'labour_type_id')
    op.drop_index('idx_fulltext_message', table_name='chat_messages', mysql_prefix='FULLTEXT')
    op.drop_index('idx_chat_pinned', table_name='chat_messages')
    op.alter_column('chat_messages', 'message',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_index('idx_chatmember_chat_deleted', table_name='chat_members')
    op.drop_column('chat_members', 'deleted_at')
    op.drop_column('chat_members', 'pinned_at')
    op.drop_column('chat_members', 'is_deleted')
    op.drop_column('chat_members', 'is_pinned')
    op.drop_column('activity_types', 'is_active')
    op.drop_index('idx_message_mentions_user', table_name='message_mentions')
    op.drop_index('idx_message_mentions_message', table_name='message_mentions')
    op.drop_table('message_mentions')
    op.drop_index('idx_delivery_message_user', table_name='message_deliveries')
    op.drop_table('message_deliveries')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###

