"""add owner fk

Revision ID: 51a405b996c1
Revises: 97a3bc8c7591
Create Date: 2026-03-30 17:01:47.859532
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a405b996c1'
down_revision = '97a3bc8c7591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'projects', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    # ### end Alembic commands ###

