"""Execution architecture linkages

Revision ID: 53b5a3e658fd
Revises: a1b2c3d4e5f6
Create Date: 2026-06-01 18:18:35.710741
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b5a3e658fd'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_site_reports', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_daily_site_reports_task_id'), 'daily_site_reports', ['task_id'], unique=False)
    op.create_foreign_key( "fk_daily_site_reports_task_id", "daily_site_reports", "tasks", ["task_id"], ["id"], ondelete="SET NULL" )
    op.add_column('dsr_labour', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dsr_labour_task_id'), 'dsr_labour', ['task_id'], unique=False)
    op.create_foreign_key( "fk_dsr_labour_task_id", "dsr_labour", "tasks", ["task_id"], ["id"], ondelete="SET NULL" )
    op.add_column('material_transactions', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_material_transactions_task_id'), 'material_transactions', ['task_id'], unique=False)
    op.create_foreign_key( "fk_material_transactions_task_id", "material_transactions", "tasks", ["task_id"], ["id"], ondelete="SET NULL" )
    op.add_column('material_usage', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_material_usage_task_id'), 'material_usage', ['task_id'], unique=False)
    op.create_foreign_key( "fk_material_usage_task_id", "material_usage", "tasks", ["task_id"], ["id"], ondelete="SET NULL" )
    # Cleaned up erroneous index drops
    op.add_column('safety_incidents', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_safety_incidents_task_id'), 'safety_incidents', ['task_id'], unique=False)
    op.create_foreign_key( "fk_safety_incidents_task_id", "safety_incidents", "tasks", ["task_id"], ["id"], ondelete="SET NULL" )
    op.add_column('site_photos', sa.Column('dsr_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_site_photos_dsr_id'), 'site_photos', ['dsr_id'], unique=False)
    op.create_foreign_key( "fk_site_photos_dsr_id", "site_photos", "daily_site_reports", ["dsr_id"], ["id"], ondelete="SET NULL" )
    op.add_column('tasks', sa.Column('milestone_id', sa.Integer(), nullable=True))
    # Cleaned up erroneous task index drop
    op.create_index(op.f('ix_tasks_milestone_id'), 'tasks', ['milestone_id'], unique=False)
    op.create_foreign_key( "fk_tasks_milestone_id", "tasks", "milestones", ["milestone_id"], ["id"], ondelete="SET NULL" )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tasks_milestone_id","tasks",type_='foreignkey')
    op.drop_index(op.f('ix_tasks_milestone_id'), table_name='tasks')
    # Cleaned up task index create
    op.drop_column('tasks', 'milestone_id')
    op.drop_constraint("fk_site_photos_dsr_id","site_photos",type_='foreignkey')
    op.drop_index(op.f('ix_site_photos_dsr_id'), table_name='site_photos')
    op.drop_column('site_photos', 'dsr_id')
    op.drop_constraint("fk_safety_incidents_task_id","safety_incidents",type_='foreignkey')
    op.drop_index(op.f('ix_safety_incidents_task_id'), table_name='safety_incidents')
    op.drop_column('safety_incidents', 'task_id')
    # Cleaned up materials index create
    op.drop_constraint("fk_material_usage_task_id","material_usage",type_='foreignkey')
    op.drop_index(op.f('ix_material_usage_task_id'), table_name='material_usage')
    op.drop_column('material_usage', 'task_id')
    op.drop_constraint("fk_material_transactions_task_id","material_transactions",type_='foreignkey')
    op.drop_index(op.f('ix_material_transactions_task_id'), table_name='material_transactions')
    op.drop_column('material_transactions', 'task_id')
    op.drop_constraint("fk_dsr_labour_task_id","dsr_labour",type_='foreignkey')
    op.drop_index(op.f('ix_dsr_labour_task_id'), table_name='dsr_labour')
    op.drop_column('dsr_labour', 'task_id')
    op.drop_constraint("fk_daily_site_reports_task_id","daily_site_reports",type_='foreignkey')
    op.drop_index(op.f('ix_daily_site_reports_task_id'), table_name='daily_site_reports')
    op.drop_column('daily_site_reports', 'task_id')
    # ### end Alembic commands ###

