"""add boq category

Revision ID: 6cb1c9355a52
Revises: 51a405b996c1
Create Date: 2026-03-30 17:21:25.905446
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb1c9355a52'
down_revision = '51a405b996c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boq_items', sa.Column('category', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_boq_items_category'), 'boq_items', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boq_items_category'), table_name='boq_items')
    op.drop_column('boq_items', 'category')
    # ### end Alembic commands ###

