"""Add GST invoice fields

Revision ID: 7957f84c4e1f
Revises: e12f819a43c9
Create Date: 2026-08-19 19:03:58.602611
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7957f84c4e1f'
down_revision = 'e12f819a43c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('party_gstin', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('cgst', sa.DECIMAL(precision=18, scale=2), server_default='0.00', nullable=True))
    op.add_column('invoices', sa.Column('sgst', sa.DECIMAL(precision=18, scale=2), server_default='0.00', nullable=True))
    op.add_column('invoices', sa.Column('igst', sa.DECIMAL(precision=18, scale=2), server_default='0.00', nullable=True))
    op.add_column('invoices', sa.Column('invoice_copy_url', sa.String(length=500), nullable=True))
    op.add_column('invoices', sa.Column('gst_document_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)

    op.add_column('vendor_bills', sa.Column('party_gstin', sa.String(length=20), nullable=True))
    op.add_column('vendor_bills', sa.Column('cgst', sa.DECIMAL(precision=18, scale=2), server_default='0.00', nullable=True))
    op.add_column('vendor_bills', sa.Column('sgst', sa.DECIMAL(precision=18, scale=2), server_default='0.00', nullable=True))
    op.add_column('vendor_bills', sa.Column('igst', sa.DECIMAL(precision=18, scale=2), server_default='0.00', nullable=True))
    op.add_column('vendor_bills', sa.Column('gst_document_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_bills', 'gst_document_url')
    op.drop_column('vendor_bills', 'igst')
    op.drop_column('vendor_bills', 'sgst')
    op.drop_column('vendor_bills', 'cgst')
    op.drop_column('vendor_bills', 'party_gstin')

    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_column('invoices', 'gst_document_url')
    op.drop_column('invoices', 'invoice_copy_url')
    op.drop_column('invoices', 'igst')
    op.drop_column('invoices', 'sgst')
    op.drop_column('invoices', 'cgst')
    op.drop_column('invoices', 'party_gstin')
    op.drop_column('invoices', 'invoice_date')
    op.drop_column('invoices', 'invoice_number')
    # ### end Alembic commands ###
