"""quotation & WorkProgress changes

Revision ID: 884c40cc5b68
Revises: ceae09082b30
Create Date: 2026-05-11 13:10:06.177092
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "884c40cc5b68"
down_revision = "ceae09082b30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("company_logo", sa.String(length=500), nullable=True),
        sa.Column("gst_number", sa.String(length=100), nullable=True),
        sa.Column("mobile_number", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("bank_name", sa.String(length=255), nullable=True),
        sa.Column("account_holder_name", sa.String(length=255), nullable=True),
        sa.Column("account_number", sa.String(length=100), nullable=True),
        sa.Column("ifsc_code", sa.String(length=100), nullable=True),
        sa.Column("upi_id", sa.String(length=255), nullable=True),
        sa.Column("signature_image", sa.String(length=500), nullable=True),
        sa.Column("terms_conditions", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quotation_master",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quotation_no", sa.String(length=50), nullable=False),
        sa.Column("client_name", sa.String(length=150), nullable=False),
        sa.Column("company_name", sa.String(length=150), nullable=True),
        sa.Column("mobile_number", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("site_address", sa.Text(), nullable=True),
        sa.Column("gst_number", sa.String(length=50), nullable=True),
        sa.Column("project_name", sa.String(length=150), nullable=False),
        sa.Column("project_type", sa.String(length=100), nullable=False),
        sa.Column("project_start_date", sa.Date(), nullable=True),
        sa.Column("project_end_date", sa.Date(), nullable=True),
        sa.Column("engineer_name", sa.String(length=150), nullable=True),
        sa.Column("work_order_no", sa.String(length=100), nullable=True),
        sa.Column("subtotal", sa.Float(), nullable=False),
        sa.Column("gst_percent", sa.Float(), nullable=False),
        sa.Column("gst_amount", sa.Float(), nullable=False),
        sa.Column("cgst_percent", sa.Float(), nullable=False),
        sa.Column("sgst_percent", sa.Float(), nullable=False),
        sa.Column("tds_percent", sa.Float(), nullable=False),
        sa.Column("cgst_amount", sa.Float(), nullable=False),
        sa.Column("sgst_amount", sa.Float(), nullable=False),
        sa.Column("tds_amount", sa.Float(), nullable=False),
        sa.Column("discount_amount", sa.Float(), nullable=False),
        sa.Column("grand_total", sa.Float(), nullable=False),
        sa.Column("advance_paid", sa.Float(), nullable=False),
        sa.Column("balance_due", sa.Float(), nullable=False),
        sa.Column("payment_mode", sa.String(length=50), nullable=True),
        sa.Column("upi_id", sa.String(length=150), nullable=True),
        sa.Column("bank_name", sa.String(length=150), nullable=True),
        sa.Column("account_holder_name", sa.String(length=150), nullable=True),
        sa.Column("account_number", sa.String(length=100), nullable=True),
        sa.Column("ifsc_code", sa.String(length=50), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column("converted_to_bill", sa.Boolean(), nullable=False),
        sa.Column("converted_to_invoice", sa.Boolean(), nullable=False),
        sa.Column("converted_to_work_order", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("terms_conditions", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SENT",
                "APPROVED",
                "REJECTED",
                "CONVERTED",
                name="quotationstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quotation_master_quotation_no"),
        "quotation_master",
        ["quotation_no"],
        unique=True,
    )
    op.create_table(
        "work_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("boq_code", sa.Integer(), nullable=True),
        sa.Column("activity_name", sa.String(length=255), nullable=False),
        sa.Column("planned_quantity", sa.DECIMAL(precision=18, scale=2), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("engineer_id", sa.Integer(), nullable=True),
        sa.Column("total_completed", sa.DECIMAL(precision=18, scale=2), nullable=True),
        sa.Column(
            "remaining_quantity", sa.DECIMAL(precision=18, scale=2), nullable=True
        ),
        sa.Column(
            "completion_percentage", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ON_TRACK",
                "DELAY",
                "COMPLETED",
                "NOT_STARTED",
                name="workactivitystatus",
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_activities_id"), "work_activities", ["id"], unique=False
    )
    op.create_table(
        "daily_progress_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("today_progress", sa.DECIMAL(precision=18, scale=2), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["work_activities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quotation_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quotation_id"], ["quotation_master.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quotation_items_item_type"),
        "quotation_items",
        ["item_type"],
        unique=False,
    )
    op.create_table(
        "measurement_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quotation_item_id", sa.Integer(), nullable=False),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("cubic_feet", sa.Float(), nullable=False),
        sa.Column("cubic_meter", sa.Float(), nullable=False),
        sa.Column("brass", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("formula_used", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["quotation_item_id"], ["quotation_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quotation_labour",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=False),
        sa.Column("labour_id", sa.Integer(), nullable=True),
        sa.Column("skill_type", sa.String(length=100), nullable=False),
        sa.Column("labour_count", sa.Integer(), nullable=False),
        sa.Column("daily_wage", sa.Float(), nullable=False),
        sa.Column("labour_days", sa.Float(), nullable=False),
        sa.Column("overtime_hours", sa.Float(), nullable=False),
        sa.Column("overtime_rate", sa.Float(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["labour_id"], ["labour.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["quotation_id"], ["quotation_master.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quotation_labour_quotation_id"),
        "quotation_labour",
        ["quotation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quotation_labour_skill_type"),
        "quotation_labour",
        ["skill_type"],
        unique=False,
    )
    op.create_table(
        "quotation_extra_charges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=False),
        sa.Column("equipment_id", sa.Integer(), nullable=True),
        sa.Column("expense_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"], ["quotation_master.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quotation_extra_charges_expense_type"),
        "quotation_extra_charges",
        ["expense_type"],
        unique=False,
    )
    op.create_table(
        "quotation_materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=True),
        sa.Column("material_name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("estimated_quantity", sa.Float(), nullable=False),
        sa.Column("estimated_rate", sa.Float(), nullable=False),
        sa.Column("estimated_amount", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"], ["quotation_master.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("invoices", sa.Column("quotation_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_invoices_quotation_id"), "invoices", ["quotation_id"], unique=True
    )
    op.create_foreign_key(
        None,
        "invoices",
        "quotation_master",
        ["quotation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("ra_bills", sa.Column("quotation_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_ra_bills_quotation_id"), "ra_bills", ["quotation_id"], unique=True
    )
    op.create_foreign_key(
        None,
        "ra_bills",
        "quotation_master",
        ["quotation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "safety_incidents",
        "safety_checklist_status",
        existing_type=mysql.ENUM("COMPLETED", "PENDING", "FAILED"),
        type_=sa.Enum("PENDING", "COMPLETED", "FAILED", name="safetycheckliststatus"),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'"),
    )
    op.alter_column(
        "safety_incidents",
        "ppe_compliance",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
        existing_server_default=sa.text("'1'"),
    )
    op.add_column(
        "suppliers", sa.Column("supplier_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "suppliers", sa.Column("contact_person", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "suppliers", sa.Column("phone_email", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "suppliers", sa.Column("gst_number", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "suppliers", sa.Column("address", sa.String(length=255), nullable=True)
    )
    op.drop_index(op.f("idx_supplier_deleted"), table_name="suppliers")
    op.drop_column("suppliers", "name")
    op.drop_column("suppliers", "contact")
    op.alter_column(
        "tasks", "created_by_user_id", existing_type=mysql.INTEGER(), nullable=False
    )
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_title"), table_name="tasks")
    op.add_column("work_orders", sa.Column("quotation_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_work_orders_quotation_id"),
        "work_orders",
        ["quotation_id"],
        unique=True,
    )
    op.create_foreign_key(
        None,
        "work_orders",
        "quotation_master",
        ["quotation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # Add discipline column to tasks
    op.add_column(
        "tasks", sa.Column("discipline", sa.String(length=100), nullable=True)
    )

    # Add work_order_id to work_activities
    op.add_column("work_activities", sa.Column("work_order_id", sa.Integer(), nullable=False))

    # Add discipline column to work_activities
    op.add_column("work_activities", sa.Column("discipline", sa.String(length=100), nullable=True))

    # Create index for work_order_id
    op.create_index(
        op.f("ix_work_activities_work_order_id"),"work_activities",["work_order_id"],unique=False,)

    # Create foreign key to work_orders table
    op.create_foreign_key(
        "fk_work_activities_work_order_id","work_activities","work_orders",["work_order_id"], ["id"],ondelete="CASCADE", )

    # ### end Alembic commands ###

def downgrade():
    # Drop foreign key
    op.drop_constraint(
        'fk_work_activities_work_order_id',
        'work_activities',
        type_='foreignkey'
    )

    # Drop index
    op.drop_index(
        op.f('ix_work_activities_work_order_id'),
        table_name='work_activities'
    )

    # Drop columns from work_activities
    op.drop_column('work_activities', 'discipline')
    op.drop_column('work_activities', 'work_order_id')

    # Drop discipline column from tasks
    op.drop_column('tasks', 'discipline')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "work_orders", type_="foreignkey")
    op.drop_index(op.f("ix_work_orders_quotation_id"), table_name="work_orders")
    op.drop_column("work_orders", "quotation_id")
    op.create_index(op.f("ix_tasks_title"), "tasks", ["title"], unique=False)
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.alter_column(
        "tasks", "created_by_user_id", existing_type=mysql.INTEGER(), nullable=True
    )
    op.add_column(
        "suppliers", sa.Column("contact", mysql.VARCHAR(length=50), nullable=True)
    )
    op.add_column(
        "suppliers", sa.Column("name", mysql.VARCHAR(length=255), nullable=False)
    )
    op.create_index(
        op.f("idx_supplier_deleted"), "suppliers", ["is_deleted"], unique=False
    )
    op.drop_column("suppliers", "address")
    op.drop_column("suppliers", "gst_number")
    op.drop_column("suppliers", "phone_email")
    op.drop_column("suppliers", "contact_person")
    op.drop_column("suppliers", "supplier_name")
    op.alter_column(
        "safety_incidents",
        "ppe_compliance",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
        existing_server_default=sa.text("'1'"),
    )
    op.alter_column(
        "safety_incidents",
        "safety_checklist_status",
        existing_type=sa.Enum(
            "PENDING", "COMPLETED", "FAILED", name="safetycheckliststatus"
        ),
        type_=mysql.ENUM("COMPLETED", "PENDING", "FAILED"),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'"),
    )
    op.drop_constraint(None, "ra_bills", type_="foreignkey")
    op.drop_index(op.f("ix_ra_bills_quotation_id"), table_name="ra_bills")
    op.drop_column("ra_bills", "quotation_id")
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_index(op.f("ix_invoices_quotation_id"), table_name="invoices")
    op.drop_column("invoices", "quotation_id")
    op.drop_table("quotation_materials")
    op.drop_index(
        op.f("ix_quotation_extra_charges_expense_type"),
        table_name="quotation_extra_charges",
    )
    op.drop_table("quotation_extra_charges")
    op.drop_index(op.f("ix_quotation_labour_skill_type"), table_name="quotation_labour")
    op.drop_index(
        op.f("ix_quotation_labour_quotation_id"), table_name="quotation_labour"
    )
    op.drop_table("quotation_labour")
    op.drop_table("measurement_details")
    op.drop_index(op.f("ix_quotation_items_item_type"), table_name="quotation_items")
    op.drop_table("quotation_items")
    op.drop_table("daily_progress_entries")
    op.drop_index(op.f("ix_work_activities_id"), table_name="work_activities")
    op.drop_table("work_activities")
    op.drop_index(
        op.f("ix_quotation_master_quotation_no"), table_name="quotation_master"
    )
    op.drop_table("quotation_master")
    op.drop_table("company_settings")
    # ### end Alembic commands ###