"""activity audit logs

Revision ID: 9e4dbce48c2b
Revises: dcdeaa3c049c
Create Date: 2026-05-14 15:28:49.147783
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4dbce48c2b'
down_revision = 'dcdeaa3c049c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['work_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_history_activity', 'activity_history', ['activity_id'], unique=False)
    op.create_index('idx_activity_history_changed_by', 'activity_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_activity_history_activity_id'), 'activity_history', ['activity_id'], unique=False)
    op.alter_column('daily_progress_entries', 'created_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'daily_progress_entries', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_tasks_assigned_user_id'), table_name='tasks')
    op.alter_column('work_activities', 'boq_code',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_activities', 'boq_code',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.drop_constraint(None, 'daily_progress_entries', type_='foreignkey')
    op.alter_column('daily_progress_entries', 'created_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_activity_history_activity_id'), table_name='activity_history')
    op.drop_index('idx_activity_history_changed_by', table_name='activity_history')
    op.drop_index('idx_activity_history_activity', table_name='activity_history')
    op.drop_table('activity_history')
    # ### end Alembic commands ###

