"""combined migrations

Revision ID: a1b2c3d4e5f6
Revises: b0090bc35520
Create Date: 2026-06-01 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'b0090bc35520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # From 3996531a57c1_add_labour_role_and_userattendance.py
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('in_time', sa.DateTime(), nullable=True),
    sa.Column('out_time', sa.DateTime(), nullable=True),
    sa.Column('check_in_image', sa.String(length=500), nullable=True),
    sa.Column('check_out_image', sa.String(length=500), nullable=True),
    sa.Column('working_hours', sa.Integer(), nullable=False),
    sa.Column('overtime_hours', sa.Integer(), nullable=False),
    sa.Column('overtime_rate', sa.Integer(), nullable=False),
    sa.Column('check_in_latitude', sa.Integer(), nullable=True),
    sa.Column('check_in_longitude', sa.Integer(), nullable=True),
    sa.Column('check_out_latitude', sa.Integer(), nullable=True),
    sa.Column('check_out_longitude', sa.Integer(), nullable=True),
    sa.Column('check_in_address', sa.String(length=255), nullable=True),
    sa.Column('check_out_address', sa.String(length=255), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('task_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_attendance_project_date', 'user_attendance', ['project_id', 'attendance_date'], unique=False)
    op.create_index(op.f('ix_user_attendance_attendance_date'), 'user_attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_user_attendance_project_id'), 'user_attendance', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_attendance_user_id'), 'user_attendance', ['user_id'], unique=False)
    op.add_column('labour', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_labour_user_id'), 'labour', ['user_id'], unique=False)
    op.create_foreign_key(None, 'labour', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # DATA MIGRATION: Create User accounts for existing Labour and migrate Attendance
    bind = op.get_bind()
    
    # 1. Create User accounts
    labours = bind.execute(sa.text("SELECT id, worker_code, labour_name FROM labour")).fetchall()
    for labour in labours:
        labour_id = labour[0]
        worker_code = labour[1]
        labour_name = labour[2]
        dummy_email = f"{worker_code}@labour.local"
        
        result = bind.execute(
            sa.text("""
                INSERT INTO users (email, full_name, role, is_active, created_at, updated_at)
                VALUES (:email, :name, 'Labour', 1, NOW(), NOW())
            """),
            {"email": dummy_email, "name": labour_name}
        )
        user_id = result.lastrowid
        
        bind.execute(
            sa.text("UPDATE labour SET user_id = :u_id WHERE id = :l_id"),
            {"u_id": user_id, "l_id": labour_id}
        )
        
    # 2. Migrate Attendance
    bind.execute(sa.text("""
        INSERT INTO user_attendance (
            user_id, project_id, attendance_date, status, in_time, out_time,
            check_in_image, check_out_image, working_hours, overtime_hours, overtime_rate,
            check_in_latitude, check_in_longitude, check_out_latitude, check_out_longitude,
            check_in_address, check_out_address, task_id, task_description,
            created_at, updated_at
        )
        SELECT 
            l.user_id, la.project_id, la.attendance_date, la.status, la.in_time, la.out_time,
            la.check_in_image, la.check_out_image, la.working_hours, la.overtime_hours, la.overtime_rate,
            la.check_in_latitude, la.check_in_longitude, la.check_out_latitude, la.check_out_longitude,
            la.check_in_address, la.check_out_address, la.task_id, la.task_description,
            la.created_at, la.updated_at
        FROM labour_attendance la
        JOIN labour l ON l.id = la.labour_id
        WHERE l.user_id IS NOT NULL
    """))

    # op.drop_index(op.f('idx_material_deleted'), table_name='materials')
    # op.drop_index(op.f('idx_material_project'), table_name='materials')
    # op.drop_index(op.f('idx_material_supplier'), table_name='materials')
    # op.drop_index(op.f('ix_tasks_assigned_user_id'), table_name='tasks')
    # ### end Alembic commands ###

    # From ce07f08570f5_add_approval_and_geofencing_to_.py
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('idx_material_deleted'), table_name='materials')
    # op.drop_index(op.f('idx_material_project'), table_name='materials')
    # op.drop_index(op.f('idx_material_supplier'), table_name='materials')
    # op.drop_index(op.f('ix_tasks_assigned_user_id'), table_name='tasks')
    op.add_column('user_attendance', sa.Column('is_approved', sa.Boolean(), nullable=False))
    op.add_column('user_attendance', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.add_column('user_attendance', sa.Column('is_outside_geofence', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'user_attendance', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # From 7e1f3b0c8d09_drop_labourattendance_table.py
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_labour_attendance_labour_id'), table_name='labour_attendance')
    # op.drop_index(op.f('ix_labour_attendance_project_id'), table_name='labour_attendance')
    op.drop_table('labour_attendance')
    # op.drop_index(op.f('idx_material_project'), table_name='materials')
    # op.drop_index(op.f('idx_material_supplier'), table_name='materials')
    # op.drop_index(op.f('ix_tasks_assigned_user_id'), table_name='tasks')
    # ### end Alembic commands ###

    # From 44f3a1f4eb53_fix_attendance_column_types_add_remarks.py
    # Add remarks column
    op.add_column('user_attendance', sa.Column('remarks', sa.String(length=500), nullable=True))

    # Fix Integer -> Float column types
    op.alter_column('user_attendance', 'working_hours',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('user_attendance', 'overtime_hours',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('user_attendance', 'overtime_rate',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('user_attendance', 'check_in_latitude',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user_attendance', 'check_in_longitude',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user_attendance', 'check_out_latitude',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user_attendance', 'check_out_longitude',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # From 3a0b6f8e61f0_phase2_shift_and_tracking.py
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('shift_start_time', sa.Time(), nullable=True))
    op.add_column('projects', sa.Column('shift_end_time', sa.Time(), nullable=True))
    op.add_column('projects', sa.Column('grace_period_minutes', sa.Integer(), nullable=False))
    op.add_column('user_attendance', sa.Column('is_late', sa.Boolean(), nullable=False))
    op.add_column('user_attendance', sa.Column('late_minutes', sa.Integer(), nullable=False))
    op.add_column('user_attendance', sa.Column('is_early_departure', sa.Boolean(), nullable=False))
    op.add_column('user_attendance', sa.Column('early_minutes', sa.Integer(), nullable=False))
    op.add_column('user_attendance', sa.Column('work_location_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

    # From 31d1058d629f_add_voice_task_assignment_fields.py
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('voice_instruction_url', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('generated_audio_url', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('original_transcription_text', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('translated_english_text', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('language_code', sa.String(length=10), nullable=True))
    op.add_column('tasks', sa.Column('audio_duration', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('task_icon', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('instruction_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

    # From 8ef123e13506_add_notifications_table.py
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # From 8ef123e13506_add_notifications_table.py
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###

    # From 31d1058d629f_add_voice_task_assignment_fields.py
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'instruction_image')
    op.drop_column('tasks', 'task_icon')
    op.drop_column('tasks', 'audio_duration')
    op.drop_column('tasks', 'language_code')
    op.drop_column('tasks', 'translated_english_text')
    op.drop_column('tasks', 'original_transcription_text')
    op.drop_column('tasks', 'generated_audio_url')
    op.drop_column('tasks', 'voice_instruction_url')
    # ### end Alembic commands ###

    # From 3a0b6f8e61f0_phase2_shift_and_tracking.py
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.drop_column('user_attendance', 'work_location_type')
    op.drop_column('user_attendance', 'early_minutes')
    op.drop_column('user_attendance', 'is_early_departure')
    op.drop_column('user_attendance', 'late_minutes')
    op.drop_column('user_attendance', 'is_late')
    op.drop_column('projects', 'grace_period_minutes')
    op.drop_column('projects', 'shift_end_time')
    op.drop_column('projects', 'shift_start_time')
    # ### end Alembic commands ###

    # From 44f3a1f4eb53_fix_attendance_column_types_add_remarks.py
    op.alter_column('user_attendance', 'check_out_longitude',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_attendance', 'check_out_latitude',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_attendance', 'check_in_longitude',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_attendance', 'check_in_latitude',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_attendance', 'overtime_rate',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_attendance', 'overtime_hours',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_attendance', 'working_hours',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('user_attendance', 'remarks')

    # From 7e1f3b0c8d09_drop_labourattendance_table.py
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('idx_material_supplier'), 'materials', ['supplier_id'], unique=False)
    op.create_index(op.f('idx_material_project'), 'materials', ['project_id'], unique=False)
    op.create_table('labour_attendance',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('labour_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attendance_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.ENUM('PRESENT', 'ABSENT', 'HALF_DAY'), nullable=False),
    sa.Column('in_time', mysql.TIME(), nullable=True),
    sa.Column('out_time', mysql.TIME(), nullable=True),
    sa.Column('working_hours', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('overtime_hours', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('overtime_rate', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('task_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('check_in_image', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('check_out_image', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('check_in_latitude', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('check_in_longitude', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('check_out_latitude', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('check_out_longitude', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('check_in_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('check_out_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['labour_id'], ['labour.id'], name=op.f('labour_attendance_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('labour_attendance_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('labour_attendance_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_labour_attendance_project_id'), 'labour_attendance', ['project_id'], unique=False)
    op.create_index(op.f('ix_labour_attendance_labour_id'), 'labour_attendance', ['labour_id'], unique=False)
    # ### end Alembic commands ###

    # From ce07f08570f5_add_approval_and_geofencing_to_.py
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_attendance', type_='foreignkey')
    op.drop_column('user_attendance', 'is_outside_geofence')
    op.drop_column('user_attendance', 'approved_by_id')
    op.drop_column('user_attendance', 'is_approved')
    op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('idx_material_supplier'), 'materials', ['supplier_id'], unique=False)
    op.create_index(op.f('idx_material_project'), 'materials', ['project_id'], unique=False)
    op.create_index(op.f('idx_material_deleted'), 'materials', ['is_deleted'], unique=False)
    # ### end Alembic commands ###

    # From 3996531a57c1_add_labour_role_and_userattendance.py
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('idx_material_supplier'), 'materials', ['supplier_id'], unique=False)
    op.create_index(op.f('idx_material_project'), 'materials', ['project_id'], unique=False)
    op.create_index(op.f('idx_material_deleted'), 'materials', ['is_deleted'], unique=False)
    op.drop_constraint(None, 'labour', type_='foreignkey')
    op.drop_index(op.f('ix_labour_user_id'), table_name='labour')
    op.drop_column('labour', 'user_id')
    op.drop_index(op.f('ix_user_attendance_user_id'), table_name='user_attendance')
    op.drop_index(op.f('ix_user_attendance_project_id'), table_name='user_attendance')
    op.drop_index(op.f('ix_user_attendance_attendance_date'), table_name='user_attendance')
    op.drop_index('idx_user_attendance_project_date', table_name='user_attendance')
    op.drop_table('user_attendance')
    # ### end Alembic commands ###
