"""owner expense model changes

Revision ID: a4068f40bc14
Revises: 47a4121119b4
Create Date: 2026-06-09 18:22:23.545865
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4068f40bc14'
down_revision = '47a4121119b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owner_transactions', 'type',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('owner_transactions', 'reference_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_index('idx_owner_reference', 'owner_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('ix_owner_transactions_reference_type'), 'owner_transactions', ['reference_type'], unique=False)
    op.create_index(op.f('ix_owner_transactions_type'), 'owner_transactions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owner_transactions_type'), table_name='owner_transactions')
    op.drop_index(op.f('ix_owner_transactions_reference_type'), table_name='owner_transactions')
    op.drop_index('idx_owner_reference', table_name='owner_transactions')
    op.alter_column('owner_transactions', 'reference_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('owner_transactions', 'type',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###

