"""Add Company model and tenant isolation

Revision ID: a53fa727c188
Revises: a0b1c2d3e4f5
Create Date: 2026-08-25 20:50:43.784829
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = "a53fa727c188"
down_revision = "a0b1c2d3e4f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subdomain", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_index(
        op.f("ix_companies_subdomain"), "companies", ["subdomain"], unique=True
    )
    op.create_index(
        op.f("ix_client_payments_client_user_id"),
        "client_payments",
        ["client_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_payments_project_id"),
        "client_payments",
        ["project_id"],
        unique=False,
    )
    op.add_column(
        "company_settings", sa.Column("company_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_company_settings_company_id"),
        "company_settings",
        ["company_id"],
        unique=True,
    )
    op.create_foreign_key(
        None,
        "company_settings",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "equipment_maintenance",
        "project_id",
        existing_type=mysql.INTEGER(),
        nullable=False,
    )
    op.create_index(
        op.f("ix_labour_contractor_id"), "labour", ["contractor_id"], unique=False
    )
    op.drop_column("labour", "daily_wage_rate")
    op.drop_column("labour", "skill_type")
    op.alter_column(
        "material_master", "unit_id", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column(
        "materials", "material_master_id", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column(
        "materials", "unit_id", existing_type=mysql.INTEGER(), nullable=False
    )
    op.add_column("projects", sa.Column("company_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_projects_company_id"), "projects", ["company_id"], unique=False
    )
    op.create_foreign_key(
        None, "projects", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("users", sa.Column("is_super_admin", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("company_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_users_company_id"), "users", ["company_id"], unique=False)
    op.create_foreign_key(
        None, "users", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_company_id"), table_name="users")
    op.drop_column("users", "company_id")
    op.drop_column("users", "is_super_admin")
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_index(op.f("ix_projects_company_id"), table_name="projects")
    op.drop_column("projects", "company_id")
    op.alter_column(
        "materials", "unit_id", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "materials", "material_master_id", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "material_master", "unit_id", existing_type=mysql.INTEGER(), nullable=True
    )
    op.add_column(
        "labour",
        sa.Column("skill_type", mysql.ENUM("SKILLED", "UNSKILLED"), nullable=True),
    )
    op.add_column(
        "labour",
        sa.Column(
            "daily_wage_rate", mysql.DECIMAL(precision=18, scale=2), nullable=True
        ),
    )
    op.drop_index(op.f("ix_labour_contractor_id"), table_name="labour")
    op.alter_column(
        "equipment_maintenance",
        "project_id",
        existing_type=mysql.INTEGER(),
        nullable=True,
    )
    op.drop_constraint(None, "company_settings", type_="foreignkey")
    op.drop_index(op.f("ix_company_settings_company_id"), table_name="company_settings")
    op.drop_column("company_settings", "company_id")
    op.drop_index(op.f("ix_client_payments_project_id"), table_name="client_payments")
    op.drop_index(
        op.f("ix_client_payments_client_user_id"), table_name="client_payments"
    )
    op.drop_index(op.f("ix_companies_subdomain"), table_name="companies")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
