"""contractor changes

Revision ID: a8de6ec505ed
Revises: 11431a1ea27a
Create Date: 2026-03-31 15:57:49.660120
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8de6ec505ed'
down_revision = '11431a1ea27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('final_area', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('approved_rate', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('extra_area', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('extra_rate', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('total_area', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_measurements_id'), 'final_measurements', ['id'], unique=False)
    op.create_index(op.f('ix_final_measurements_project_id'), 'final_measurements', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_final_measurements_project_id'), table_name='final_measurements')
    op.drop_index(op.f('ix_final_measurements_id'), table_name='final_measurements')
    op.drop_table('final_measurements')
    # ### end Alembic commands ###

