"""udpate data

Revision ID: a94ed8ba78f7
Revises: 380a43aa03a9
Create Date: 2026-04-02 12:44:53.981202
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94ed8ba78f7'
down_revision = '380a43aa03a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_site_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('work_done', sa.Text(), nullable=False),
    sa.Column('work_planned', sa.Text(), nullable=True),
    sa.Column('labour_count', sa.Integer(), nullable=True),
    sa.Column('material_used', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_site_reports_id'), 'daily_site_reports', ['id'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_project_id'), 'daily_site_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_report_date'), 'daily_site_reports', ['report_date'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_table('ra_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=False),
    sa.Column('work_description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=3), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('gross_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('deductions', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('net_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('gst_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number')
    )
    op.create_index(op.f('ix_ra_bills_contractor_id'), 'ra_bills', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_ra_bills_id'), 'ra_bills', ['id'], unique=False)
    op.create_index(op.f('ix_ra_bills_project_id'), 'ra_bills', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ra_bills_project_id'), table_name='ra_bills')
    op.drop_index(op.f('ix_ra_bills_id'), table_name='ra_bills')
    op.drop_index(op.f('ix_ra_bills_contractor_id'), table_name='ra_bills')
    op.drop_table('ra_bills')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_daily_site_reports_report_date'), table_name='daily_site_reports')
    op.drop_index(op.f('ix_daily_site_reports_project_id'), table_name='daily_site_reports')
    op.drop_index(op.f('ix_daily_site_reports_id'), table_name='daily_site_reports')
    op.drop_table('daily_site_reports')
    # ### end Alembic commands ###

