"""update labour and user models

Revision ID: aaf8fb43b0e4
Revises: b39f495b768b
Create Date: 2026-04-22 22:52:30.509460
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaf8fb43b0e4'
down_revision = 'b39f495b768b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_supplier_deleted', 'suppliers', ['is_deleted'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity'), 'activity_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_performed_by'), 'activity_logs', ['performed_by'], unique=False)
    op.create_table('user_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('change_group_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_audit_logs_change_group_id'), 'user_audit_logs', ['change_group_id'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_changed_at'), 'user_audit_logs', ['changed_at'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_user_id'), 'user_audit_logs', ['user_id'], unique=False)
    op.create_table('labour_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labour_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['labour_id'], ['labour.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('labour_id', 'project_id', name='uq_labour_project')
    )
    op.create_index(op.f('ix_labour_project_labour_id'), 'labour_project', ['labour_id'], unique=False)
    op.create_index(op.f('ix_labour_project_project_id'), 'labour_project', ['project_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=3), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_po_project', 'purchase_orders', ['project_id'], unique=False)
    op.create_table('material_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE', 'USAGE', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', name='ledger_type_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=3), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('payment_pending', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('issue_type', sa.Enum('SYSTEM', 'SITE', 'DAMAGE', 'LOSS', 'VENDOR', 'TRANSFER', 'ADJUSTMENT', 'PURCHASE', name='ledger_issue_type_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_material', 'material_ledger', ['material_id'], unique=False)
    op.create_index('idx_ledger_reference', 'material_ledger', ['reference_id'], unique=False)
    op.create_table('material_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('PURCHASE', 'USAGE', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', name='transaction_type_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=3), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=18, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('payment_pending', sa.DECIMAL(precision=18, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('issue_type', sa.Enum('SYSTEM', 'SITE', 'DAMAGE', 'LOSS', 'VENDOR', 'TRANSFER', 'ADJUSTMENT', 'PURCHASE', name='issue_type_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tx_material', 'material_transactions', ['material_id'], unique=False)
    op.create_index('idx_tx_project', 'material_transactions', ['project_id'], unique=False)
    op.create_index('idx_tx_reference', 'material_transactions', ['reference_id'], unique=False)
    op.create_table('material_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('from_project_id', sa.Integer(), nullable=False),
    sa.Column('to_project_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['to_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transfer_material', 'material_transfers', ['material_id'], unique=False)
    op.alter_column('dsr_labour', 'status',
               existing_type=mysql.ENUM('PRESENT', 'ABSENT', 'HALF'),
               type_=sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', name='attendancestatus'),
               existing_nullable=False)
    op.drop_index(op.f('ix_labour_project_id'), table_name='labour')
    op.drop_constraint(op.f('labour_ibfk_2'), 'labour', type_='foreignkey')
    op.drop_column('labour', 'project_id')
    op.add_column('labour_attendance', sa.Column('check_in_image', sa.String(length=500), nullable=True))
    op.add_column('labour_attendance', sa.Column('check_out_image', sa.String(length=500), nullable=True))
    op.add_column('labour_attendance', sa.Column('check_in_latitude', sa.DECIMAL(precision=9, scale=6), nullable=True))
    op.add_column('labour_attendance', sa.Column('check_in_longitude', sa.DECIMAL(precision=9, scale=6), nullable=True))
    op.add_column('labour_attendance', sa.Column('check_out_latitude', sa.DECIMAL(precision=9, scale=6), nullable=True))
    op.add_column('labour_attendance', sa.Column('check_out_longitude', sa.DECIMAL(precision=9, scale=6), nullable=True))
    op.add_column('labour_attendance', sa.Column('check_in_address', sa.String(length=255), nullable=True))
    op.add_column('labour_attendance', sa.Column('check_out_address', sa.String(length=255), nullable=True))
    op.add_column('labour_attendance', sa.Column('task_id', sa.Integer(), nullable=True))
    op.alter_column('labour_attendance', 'status',
               existing_type=mysql.ENUM('PRESENT', 'ABSENT', 'HALF'),
               type_=sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', name='attendancestatus'),
               existing_nullable=False)
    op.drop_index(op.f('idx_labour_attendance_labour_date'), table_name='labour_attendance')
    op.create_index('idx_labour_attendance_project_date', 'labour_attendance', ['project_id', 'attendance_date'], unique=False)
    op.create_foreign_key(None, 'labour_attendance', 'tasks', ['task_id'], ['id'])
    op.alter_column('material_usage', 'material_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('material_usage', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('material_usage', 'usage_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_material_usage_usage_date'), table_name='material_usage')
    op.create_index('idx_usage_material', 'material_usage', ['material_id'], unique=False)
    op.drop_constraint(op.f('material_usage_ibfk_1'), 'material_usage', type_='foreignkey')
    op.create_foreign_key(None, 'material_usage', 'materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.add_column('materials', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('materials', sa.Column('supplier_id', sa.Integer(), nullable=False))
    op.add_column('materials', sa.Column('advance_amount', sa.DECIMAL(precision=18, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('materials', sa.Column('minimum_stock_level', sa.DECIMAL(precision=18, scale=3), server_default=sa.text('0.000'), nullable=False))
    op.alter_column('materials', 'rate_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('FIXED', 'PER_UNIT', 'PER_KG', 'PER_TON', 'PER_BAG', name='rate_type_enum', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.drop_index(op.f('idx_material_category'), table_name='materials')
    op.drop_index(op.f('ix_materials_material_name'), table_name='materials')
    op.create_index('idx_material_deleted', 'materials', ['is_deleted'], unique=False)
    op.create_index('idx_material_supplier', 'materials', ['supplier_id'], unique=False)
    op.create_unique_constraint('unique_material_per_project_supplier', 'materials', ['project_id', 'material_name', 'supplier_id'])
    op.drop_constraint(op.f('materials_ibfk_1'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'projects', ['project_id'], ['id'])
    op.drop_column('materials', 'supplier_name')
    op.drop_index(op.f('bill_number'), table_name='ra_bills')
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.Date(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.create_index(op.f('bill_number'), 'ra_bills', ['bill_number'], unique=True)
    op.add_column('materials', sa.Column('supplier_name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_ibfk_1'), 'materials', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_material_per_project_supplier', 'materials', type_='unique')
    op.drop_index('idx_material_supplier', table_name='materials')
    op.drop_index('idx_material_deleted', table_name='materials')
    op.create_index(op.f('ix_materials_material_name'), 'materials', ['material_name'], unique=False)
    op.create_index(op.f('idx_material_category'), 'materials', ['category'], unique=False)
    op.alter_column('materials', 'rate_type',
               existing_type=sa.Enum('FIXED', 'PER_UNIT', 'PER_KG', 'PER_TON', 'PER_BAG', name='rate_type_enum', native_enum=False, create_constraint=True),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('materials', 'minimum_stock_level')
    op.drop_column('materials', 'advance_amount')
    op.drop_column('materials', 'supplier_id')
    op.drop_column('materials', 'is_deleted')
    op.drop_constraint(None, 'material_usage', type_='foreignkey')
    op.create_foreign_key(op.f('material_usage_ibfk_1'), 'material_usage', 'materials', ['material_id'], ['id'])
    op.drop_index('idx_usage_material', table_name='material_usage')
    op.create_index(op.f('ix_material_usage_usage_date'), 'material_usage', ['usage_date'], unique=False)
    op.alter_column('material_usage', 'usage_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('material_usage', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('material_usage', 'material_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'labour_attendance', type_='foreignkey')
    op.drop_index('idx_labour_attendance_project_date', table_name='labour_attendance')
    op.create_index(op.f('idx_labour_attendance_labour_date'), 'labour_attendance', ['labour_id', 'attendance_date'], unique=False)
    op.alter_column('labour_attendance', 'status',
               existing_type=sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', name='attendancestatus'),
               type_=mysql.ENUM('PRESENT', 'ABSENT', 'HALF'),
               existing_nullable=False)
    op.drop_column('labour_attendance', 'task_id')
    op.drop_column('labour_attendance', 'check_out_address')
    op.drop_column('labour_attendance', 'check_in_address')
    op.drop_column('labour_attendance', 'check_out_longitude')
    op.drop_column('labour_attendance', 'check_out_latitude')
    op.drop_column('labour_attendance', 'check_in_longitude')
    op.drop_column('labour_attendance', 'check_in_latitude')
    op.drop_column('labour_attendance', 'check_out_image')
    op.drop_column('labour_attendance', 'check_in_image')
    op.add_column('labour', sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('labour_ibfk_2'), 'labour', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uq_project_aadhaar'), 'labour', ['project_id', 'aadhaar_number'], unique=True)
    op.create_index(op.f('ix_labour_project_id'), 'labour', ['project_id'], unique=False)
    op.alter_column('dsr_labour', 'status',
               existing_type=sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', name='attendancestatus'),
               type_=mysql.ENUM('PRESENT', 'ABSENT', 'HALF'),
               existing_nullable=False)
    op.drop_index('idx_transfer_material', table_name='material_transfers')
    op.drop_table('material_transfers')
    op.drop_index('idx_tx_reference', table_name='material_transactions')
    op.drop_index('idx_tx_project', table_name='material_transactions')
    op.drop_index('idx_tx_material', table_name='material_transactions')
    op.drop_table('material_transactions')
    op.drop_index('idx_ledger_reference', table_name='material_ledger')
    op.drop_index('idx_ledger_material', table_name='material_ledger')
    op.drop_table('material_ledger')
    op.drop_index('idx_po_project', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_labour_project_project_id'), table_name='labour_project')
    op.drop_index(op.f('ix_labour_project_labour_id'), table_name='labour_project')
    op.drop_table('labour_project')
    op.drop_index(op.f('ix_user_audit_logs_user_id'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_changed_at'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_change_group_id'), table_name='user_audit_logs')
    op.drop_table('user_audit_logs')
    op.drop_index(op.f('ix_activity_logs_performed_by'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('idx_supplier_deleted', table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###

