"""add new models

Revision ID: b39f495b768b
Revises: caf115acc2e0
Create Date: 2026-04-16 23:40:04.402534
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b39f495b768b'
down_revision = 'caf115acc2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('cad_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cad_conversions_id'), 'cad_conversions', ['id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('work_order_number', sa.String(length=50), nullable=False),
    sa.Column('work_description', sa.String(length=255), nullable=False),
    sa.Column('total_quantity', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('completed_quantity', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_number')
    )
    op.create_index(op.f('ix_work_orders_contractor_id'), 'work_orders', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_project_id'), 'work_orders', ['project_id'], unique=False)
    op.create_table('dsr_labour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dsr_id', sa.Integer(), nullable=False),
    sa.Column('labour_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF', name='attendancestatus'), nullable=False),
    sa.Column('working_hours', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('overtime_hours >= 0'),
    sa.CheckConstraint('working_hours >= 0'),
    sa.ForeignKeyConstraint(['dsr_id'], ['daily_site_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['labour_id'], ['labour.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dsr_id', 'labour_id', name='uq_dsr_labour')
    )
    op.create_index('idx_dsr_labour_dsr', 'dsr_labour', ['dsr_id'], unique=False)
    op.create_index('idx_dsr_labour_dsr_labour', 'dsr_labour', ['dsr_id', 'labour_id'], unique=False)
    op.create_index('idx_dsr_labour_labour', 'dsr_labour', ['labour_id'], unique=False)
    op.create_index(op.f('ix_dsr_labour_dsr_id'), 'dsr_labour', ['dsr_id'], unique=False)
    op.create_index(op.f('ix_dsr_labour_labour_id'), 'dsr_labour', ['labour_id'], unique=False)
    op.create_index(op.f('ix_contractors_contact_number'), 'contractors', ['contact_number'], unique=True)
    op.add_column('daily_site_reports', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column(
        'daily_site_reports',
        sa.Column('business_id', sa.String(length=20), nullable=False)
    )

    op.create_index(
        'ix_daily_site_reports_business_id',
        'daily_site_reports',
        ['business_id'],
        unique=True
    )
    op.add_column('daily_site_reports', sa.Column('contractor_id', sa.Integer(), nullable=True))
    op.add_column('daily_site_reports', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('daily_site_reports', sa.Column('total_labour', sa.Integer(), nullable=True))
    op.add_column('daily_site_reports', sa.Column('skilled_labour', sa.Integer(), nullable=True))
    op.add_column('daily_site_reports', sa.Column('unskilled_labour', sa.Integer(), nullable=True))
    op.create_index('idx_dsr_lat_lng', 'daily_site_reports', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_contractor_id'), 'daily_site_reports', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_created_by_id'), 'daily_site_reports', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_status'), 'daily_site_reports', ['status'], unique=False)
    op.drop_constraint(op.f('daily_site_reports_ibfk_1'), 'daily_site_reports', type_='foreignkey')
    op.create_foreign_key(None, 'daily_site_reports', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'daily_site_reports', 'contractors', ['contractor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('daily_site_reports', 'created_by_user_id')
    op.drop_column('daily_site_reports', 'contractor_name')
    op.drop_column('daily_site_reports', 'labour_count')
    op.alter_column('labour', 'skill_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('SKILLED', 'UNSKILLED', name='skilltype'),
               existing_nullable=False)
    op.alter_column('labour', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'INACTIVE', name='labourstatus'),
               existing_nullable=False)
    op.create_index(op.f('ix_labour_aadhaar_number'), 'labour', ['aadhaar_number'], unique=False)
    op.create_unique_constraint('uq_project_aadhaar', 'labour', ['project_id', 'aadhaar_number'])
    op.alter_column('labour_attendance', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PRESENT', 'ABSENT', 'HALF', name='attendancestatus'),
               existing_nullable=False)
    op.alter_column('labour_payroll', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PAID', 'PARTIAL', name='payrollstatus'),
               existing_nullable=True)
    op.add_column('owners', sa.Column('owner_code', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_owners_owner_code'), 'owners', ['owner_code'], unique=True)
    op.add_column('projects', sa.Column('business_id', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_projects_business_id'), 'projects', ['business_id'], unique=True)
    op.add_column(
        'issues',
        sa.Column('business_id', sa.String(length=20), nullable=False)
    )

    op.create_index(
        'ix_issues_business_id',
        'issues',
        ['business_id'],
        unique=True
    )
    op.add_column('ra_bills', sa.Column('work_order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ra_bills_bill_number'), 'ra_bills', ['bill_number'], unique=True)
    op.create_foreign_key(None, 'ra_bills', 'work_orders', ['work_order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ra_bills', type_='foreignkey')
    op.create_index(op.f('bill_number'), 'ra_bills', ['bill_number'], unique=True)
    op.drop_column('ra_bills', 'work_order_id')
    op.drop_index('ix_issues_business_id', table_name='issues')
    op.drop_column('issues', 'business_id')
    op.drop_index('ix_daily_site_reports_business_id', table_name='daily_site_reports')
    op.drop_column('daily_site_reports', 'business_id')
    op.drop_column('projects', 'business_id')
    op.drop_column('owners', 'owner_code')
    op.alter_column('labour_payroll', 'status',
               existing_type=sa.Enum('PENDING', 'PAID', 'PARTIAL', name='payrollstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('labour_attendance', 'status',
               existing_type=sa.Enum('PRESENT', 'ABSENT', 'HALF', name='attendancestatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint('uq_project_aadhaar', 'labour', type_='unique')
    op.alter_column('labour', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', name='labourstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('labour', 'skill_type',
               existing_type=sa.Enum('SKILLED', 'UNSKILLED', name='skilltype'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('daily_site_reports', sa.Column('labour_count', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_site_reports', sa.Column('contractor_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('daily_site_reports', sa.Column('created_by_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'daily_site_reports', type_='foreignkey')
    op.drop_constraint(None, 'daily_site_reports', type_='foreignkey')
    op.create_foreign_key(op.f('daily_site_reports_ibfk_1'), 'daily_site_reports', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_daily_site_reports_created_by_user_id'), 'daily_site_reports', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_daily_site_reports_contractor_name'), 'daily_site_reports', ['contractor_name'], unique=False)
    op.drop_column('daily_site_reports', 'unskilled_labour')
    op.drop_column('daily_site_reports', 'skilled_labour')
    op.drop_column('daily_site_reports', 'total_labour')
    op.drop_column('daily_site_reports', 'status')
    op.drop_column('daily_site_reports', 'contractor_id')
    op.drop_column('daily_site_reports', 'created_by_id')
    op.drop_table('dsr_labour')
    op.drop_table('work_orders')
    op.drop_table('cad_conversions')
    op.drop_table('approvals')
    # ### end Alembic commands ###

