"""udpate data

Revision ID: b57271cc9872
Revises: a94ed8ba78f7
Create Date: 2026-04-02 23:32:56.871560
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57271cc9872'
down_revision = 'a94ed8ba78f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

