"""material equipment schema and cleanup

Revision ID: e13e5f557063
Revises: 3bcfb82f7a21
Create Date: 2026-06-26 16:43:00.734345
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e13e5f557063'
down_revision = '3bcfb82f7a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gst_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_period', sa.String(length=20), nullable=False),
    sa.Column('return_type', sa.String(length=50), nullable=False),
    sa.Column('taxable_value', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('gst_liability', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('itc_available', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('net_gst_payable', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_returns_filing_period'), 'gst_returns', ['filing_period'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('is_reconciled', sa.Integer(), nullable=True),
    sa.Column('matched_journal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['matched_journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_reference_number'), 'bank_transactions', ['reference_number'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.create_table('fund_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_transfers_transfer_date'), 'fund_transfers', ['transfer_date'], unique=False)
    op.create_table('task_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('boq_item_id', sa.Integer(), nullable=True),
    sa.Column('purchase_type', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_equipment_purchase_asset_id'), 'equipment_purchase', ['asset_id'], unique=False)
    op.create_index(op.f('ix_equipment_purchase_boq_item_id'), 'equipment_purchase', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_equipment_purchase_purchase_type'), 'equipment_purchase', ['purchase_type'], unique=False)
    op.create_table('vendor_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_bills_bill_number'), 'vendor_bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_vendor_bills_project_id'), 'vendor_bills', ['project_id'], unique=False)
    op.create_index(op.f('ix_vendor_bills_purchase_order_id'), 'vendor_bills', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_vendor_bills_supplier_id'), 'vendor_bills', ['supplier_id'], unique=False)
    # op.drop_index(op.f('idx_message_created'), table_name='messages')
    # op.drop_index(op.f('idx_message_project'), table_name='messages')
    # op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.add_column('drawing_documents', sa.Column('is_folder', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('drawing_documents', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('drawing_documents', 'version',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('drawing_documents', 'file_url',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.create_index(op.f('ix_drawing_documents_is_folder'), 'drawing_documents', ['is_folder'], unique=False)
    op.create_index(op.f('ix_drawing_documents_parent_id'), 'drawing_documents', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'drawing_documents', 'drawing_documents', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('equipment_maintenance', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('equipment_maintenance', sa.Column('boq_item_id', sa.Integer(), nullable=True))
    op.add_column('equipment_maintenance', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('equipment_maintenance', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_equipment_maintenance_boq_item_id'), 'equipment_maintenance', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_equipment_maintenance_is_completed'), 'equipment_maintenance', ['is_completed'], unique=False)
    op.create_foreign_key(None, 'equipment_maintenance', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'equipment_maintenance', 'boq_items', ['boq_item_id'], ['id'], ondelete='SET NULL')
    op.add_column('equipment_rental', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('equipment_rental', sa.Column('boq_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_equipment_rental_boq_item_id'), 'equipment_rental', ['boq_item_id'], unique=False)
    op.create_foreign_key(None, 'equipment_rental', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'equipment_rental', 'boq_items', ['boq_item_id'], ['id'], ondelete='SET NULL')
    op.add_column('equipment_usage', sa.Column('boq_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_equipment_usage_boq_item_id'), 'equipment_usage', ['boq_item_id'], unique=False)
    op.create_unique_constraint('uq_equipment_usage_date', 'equipment_usage', ['equipment_id', 'usage_date'])
    op.create_foreign_key(None, 'equipment_usage', 'boq_items', ['boq_item_id'], ['id'], ondelete='SET NULL')
    op.add_column('labour_payroll', sa.Column('advance_adjusted', sa.DECIMAL(precision=18, scale=2), server_default='0', nullable=True))
    op.add_column('labour_payroll', sa.Column('remarks', sa.String(length=500), nullable=True))
    op.add_column('material_ledger', sa.Column('boq_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_material_ledger_boq_item_id'), 'material_ledger', ['boq_item_id'], unique=False)
    op.create_foreign_key(None, 'material_ledger', 'boq_items', ['boq_item_id'], ['id'], ondelete='SET NULL')
    op.add_column('material_master', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'material_master', 'units', ['unit_id'], ['id'])
    op.drop_column('material_master', 'unit')
    op.add_column('material_transactions', sa.Column('boq_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_material_transactions_boq_item_id'), 'material_transactions', ['boq_item_id'], unique=False)
    op.create_foreign_key(None, 'material_transactions', 'boq_items', ['boq_item_id'], ['id'], ondelete='SET NULL')
    op.add_column('material_usage', sa.Column('boq_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_material_usage_boq_item_id'), 'material_usage', ['boq_item_id'], unique=False)
    op.create_foreign_key(None, 'material_usage', 'boq_items', ['boq_item_id'], ['id'], ondelete='SET NULL')
    op.add_column('materials', sa.Column('material_master_id', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('unique_material_per_project_supplier'), table_name='materials')
    op.create_index(op.f('ix_materials_material_master_id'), 'materials', ['material_master_id'], unique=False)
    op.create_unique_constraint('uq_project_master_supplier', 'materials', ['project_id', 'material_master_id', 'supplier_id'])
    op.create_foreign_key(None, 'materials', 'units', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'material_master', ['material_master_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('materials', 'unit')
    op.add_column('purchase_orders', sa.Column('boq_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_boq_item_id'), 'purchase_orders', ['boq_item_id'], unique=False)
    op.create_foreign_key(None, 'purchase_orders', 'boq_items', ['boq_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_boq_item_id'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'boq_item_id')
    op.add_column('materials', sa.Column('unit', mysql.VARCHAR(length=50), server_default=sa.text("'unit'"), nullable=False))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint('uq_project_master_supplier', 'materials', type_='unique')
    op.drop_index(op.f('ix_materials_material_master_id'), table_name='materials')
    op.create_index(op.f('unique_material_per_project_supplier'), 'materials', ['project_id', 'material_name', 'supplier_id'], unique=True)
    op.drop_column('materials', 'unit_id')
    op.drop_column('materials', 'material_master_id')
    op.drop_constraint(None, 'material_usage', type_='foreignkey')
    op.drop_index(op.f('ix_material_usage_boq_item_id'), table_name='material_usage')
    op.drop_column('material_usage', 'boq_item_id')
    op.drop_constraint(None, 'material_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_material_transactions_boq_item_id'), table_name='material_transactions')
    op.drop_column('material_transactions', 'boq_item_id')
    op.add_column('material_master', sa.Column('unit', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'material_master', type_='foreignkey')
    op.drop_column('material_master', 'unit_id')
    op.drop_constraint(None, 'material_ledger', type_='foreignkey')
    op.drop_index(op.f('ix_material_ledger_boq_item_id'), table_name='material_ledger')
    op.drop_column('material_ledger', 'boq_item_id')
    op.drop_column('labour_payroll', 'remarks')
    op.drop_column('labour_payroll', 'advance_adjusted')
    op.drop_constraint(None, 'equipment_usage', type_='foreignkey')
    op.drop_constraint('uq_equipment_usage_date', 'equipment_usage', type_='unique')
    op.drop_index(op.f('ix_equipment_usage_boq_item_id'), table_name='equipment_usage')
    op.drop_column('equipment_usage', 'boq_item_id')
    op.drop_constraint(None, 'equipment_rental', type_='foreignkey')
    op.drop_constraint(None, 'equipment_rental', type_='foreignkey')
    op.drop_index(op.f('ix_equipment_rental_boq_item_id'), table_name='equipment_rental')
    op.drop_column('equipment_rental', 'boq_item_id')
    op.drop_column('equipment_rental', 'project_id')
    op.drop_constraint(None, 'equipment_maintenance', type_='foreignkey')
    op.drop_constraint(None, 'equipment_maintenance', type_='foreignkey')
    op.drop_index(op.f('ix_equipment_maintenance_is_completed'), table_name='equipment_maintenance')
    op.drop_index(op.f('ix_equipment_maintenance_boq_item_id'), table_name='equipment_maintenance')
    op.drop_column('equipment_maintenance', 'completed_at')
    op.drop_column('equipment_maintenance', 'is_completed')
    op.drop_column('equipment_maintenance', 'boq_item_id')
    op.drop_column('equipment_maintenance', 'project_id')
    op.drop_constraint(None, 'drawing_documents', type_='foreignkey')
    op.drop_index(op.f('ix_drawing_documents_parent_id'), table_name='drawing_documents')
    op.drop_index(op.f('ix_drawing_documents_is_folder'), table_name='drawing_documents')
    op.alter_column('drawing_documents', 'file_url',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('drawing_documents', 'version',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('drawing_documents', 'parent_id')
    op.drop_column('drawing_documents', 'is_folder')
    op.create_table('messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.ENUM('SENT', 'DELIVERED', 'READ'), nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attachment_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('messages_ibfk_1')),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], name=op.f('messages_ibfk_2')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('messages_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('idx_message_project'), 'messages', ['project_id'], unique=False)
    op.create_index(op.f('idx_message_created'), 'messages', ['created_at'], unique=False)
    op.drop_index(op.f('ix_vendor_bills_supplier_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_purchase_order_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_project_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_bill_number'), table_name='vendor_bills')
    op.drop_table('vendor_bills')
    op.drop_index(op.f('ix_equipment_purchase_purchase_type'), table_name='equipment_purchase')
    op.drop_index(op.f('ix_equipment_purchase_boq_item_id'), table_name='equipment_purchase')
    op.drop_index(op.f('ix_equipment_purchase_asset_id'), table_name='equipment_purchase')
    op.drop_table('equipment_purchase')
    op.drop_table('task_requests')
    op.drop_index(op.f('ix_fund_transfers_transfer_date'), table_name='fund_transfers')
    op.drop_table('fund_transfers')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_reference_number'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_gst_returns_filing_period'), table_name='gst_returns')
    op.drop_table('gst_returns')
    # ### end Alembic commands ###

