"""sync work_activity

Revision ID: e1509b93a099
Revises: 78a8c7c5cff5
Create Date: 2026-07-26 18:09:13.561944
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e1509b93a099"
down_revision = "78a8c7c5cff5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_activities",
        "created_at",
        existing_type=mysql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.create_index(
        op.f("ix_work_activities_status"), "work_activities", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_activities_status"), table_name="work_activities")
    op.alter_column(
        "work_activities",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=mysql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("(now())"),
    )
    # ### end Alembic commands ###
