"""Add new table

Revision ID: e3fc2b7d2646
Revises: f34b0ff746cb
Create Date: 2026-06-07 22:23:23.905112
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3fc2b7d2646'
down_revision = 'f34b0ff746cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_ot_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.Enum('MULTIPLIER', 'FIXED_RATE', name='otpolicytype'), nullable=False),
    sa.Column('normal_day_multiplier', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('sunday_multiplier', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('holiday_multiplier', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fixed_ot_rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.drop_constraint(op.f('dsr_photos_ibfk_3'), 'dsr_photos', type_='foreignkey')
    op.drop_constraint(op.f('dsr_photos_ibfk_2'), 'dsr_photos', type_='foreignkey')
    op.drop_table('dsr_task_entries')
    op.drop_column('dsr_photos', 'uploaded_by_id')
    op.drop_column('dsr_photos', 'caption')
    op.drop_column('dsr_photos', 'task_entry_id')
    op.add_column('labour', sa.Column('mobile_number', sa.String(length=15), nullable=True))
    op.add_column('labour', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('labour', sa.Column('profile_image', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_labour_mobile_number'), 'labour', ['mobile_number'], unique=True)
    op.create_unique_constraint(None, 'labour', ['email'])
    op.create_index('idx_material_deleted', 'materials', ['is_deleted'], unique=False)
    op.create_unique_constraint('unique_material_per_project_supplier', 'materials', ['project_id', 'material_name', 'supplier_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_material_per_project_supplier', 'materials', type_='unique')
    op.drop_index('idx_material_deleted', table_name='materials')
    op.drop_constraint(None, 'labour', type_='unique')
    op.drop_index(op.f('ix_labour_mobile_number'), table_name='labour')
    op.drop_column('labour', 'profile_image')
    op.drop_column('labour', 'email')
    op.drop_column('labour', 'mobile_number')
    op.add_column('dsr_photos', sa.Column('task_entry_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dsr_photos', sa.Column('caption', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('dsr_photos', sa.Column('uploaded_by_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('dsr_photos_ibfk_2'), 'dsr_photos', 'dsr_task_entries', ['task_entry_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('dsr_photos_ibfk_3'), 'dsr_photos', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_dsr_photos_uploaded_by_id'), 'dsr_photos', ['uploaded_by_id'], unique=False)
    op.create_index(op.f('ix_dsr_photos_task_entry_id'), 'dsr_photos', ['task_entry_id'], unique=False)
    op.create_table('dsr_task_entries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dsr_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work_done', mysql.TEXT(), nullable=False),
    sa.Column('work_planned', mysql.TEXT(), nullable=True),
    sa.Column('labour_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('machinery_used', mysql.TEXT(), nullable=True),
    sa.Column('material_used', mysql.TEXT(), nullable=True),
    sa.Column('issues', mysql.TEXT(), nullable=True),
    sa.Column('safety_observations', mysql.TEXT(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('completion_percentage', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['dsr_id'], ['daily_site_reports.id'], name=op.f('dsr_task_entries_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('dsr_task_entries_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_dsr_task_entries_task_id'), 'dsr_task_entries', ['task_id'], unique=False)
    op.create_index(op.f('ix_dsr_task_entries_dsr_id'), 'dsr_task_entries', ['dsr_id'], unique=False)
    op.drop_table('project_ot_policy')
    # ### end Alembic commands ###

