"""task request and reports

Revision ID: e486a7fc6d74
Revises: ef2999b755b6
Create Date: 2026-06-22 11:50:01.081178
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e486a7fc6d74'
down_revision = 'ef2999b755b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_type', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['equipment.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_equipment_purchase_asset_id'), 'equipment_purchase', ['asset_id'], unique=False)
    op.create_index(op.f('ix_equipment_purchase_purchase_type'), 'equipment_purchase', ['purchase_type'], unique=False)
    op.drop_table('messages')
    op.add_column('equipment_maintenance', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('equipment_maintenance', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_equipment_maintenance_is_completed'), 'equipment_maintenance', ['is_completed'], unique=False)
    op.create_unique_constraint('uq_equipment_usage_date', 'equipment_usage', ['equipment_id', 'usage_date'])
    op.add_column('material_master', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'material_master', 'units', ['unit_id'], ['id'])
    op.drop_column('material_master', 'unit')
    op.add_column('materials', sa.Column('material_master_id', sa.Integer(), nullable=False))
    op.add_column('materials', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('unique_material_per_project_supplier'), table_name='materials')
    op.create_index(op.f('ix_materials_material_master_id'), 'materials', ['material_master_id'], unique=False)
    op.create_unique_constraint('uq_project_master_supplier', 'materials', ['project_id', 'material_master_id', 'supplier_id'])
    op.create_foreign_key(None, 'materials', 'units', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'material_master', ['material_master_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('materials', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('unit', mysql.VARCHAR(length=50), server_default=sa.text("'unit'"), nullable=False))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint('uq_project_master_supplier', 'materials', type_='unique')
    op.drop_index(op.f('ix_materials_material_master_id'), table_name='materials')
    op.create_index(op.f('unique_material_per_project_supplier'), 'materials', ['project_id', 'material_name', 'supplier_id'], unique=True)
    op.drop_column('materials', 'unit_id')
    op.drop_column('materials', 'material_master_id')
    op.add_column('material_master', sa.Column('unit', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'material_master', type_='foreignkey')
    op.drop_column('material_master', 'unit_id')
    op.add_column('labour', sa.Column('skill_type', mysql.ENUM('SKILLED', 'UNSKILLED'), nullable=True))
    op.add_column('labour', sa.Column('daily_wage_rate', mysql.DECIMAL(precision=18, scale=2), nullable=True))
    op.drop_constraint('uq_equipment_usage_date', 'equipment_usage', type_='unique')
    op.drop_index(op.f('ix_equipment_maintenance_is_completed'), table_name='equipment_maintenance')
    op.drop_column('equipment_maintenance', 'completed_at')
    op.drop_column('equipment_maintenance', 'is_completed')
    op.create_table('messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.ENUM('SENT', 'DELIVERED', 'READ'), nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attachment_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('messages_ibfk_1')),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], name=op.f('messages_ibfk_2')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('messages_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('idx_message_project'), 'messages', ['project_id'], unique=False)
    op.create_index(op.f('idx_message_created'), 'messages', ['created_at'], unique=False)
    op.drop_index(op.f('ix_equipment_purchase_purchase_type'), table_name='equipment_purchase')
    op.drop_index(op.f('ix_equipment_purchase_asset_id'), table_name='equipment_purchase')
    op.drop_table('equipment_purchase')
    op.drop_table('task_requests')
    # ### end Alembic commands ###

