"""phase3_commercial_billing_engine

Revision ID: f34b0ff746cb
Revises: f5ec32624af9
Create Date: 2026-06-02 14:44:02.384851
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34b0ff746cb'
down_revision = 'f5ec32624af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('final_measurements', sa.Column('task_id', sa.Integer(), nullable=True))
#     op.add_column('final_measurements', sa.Column('boq_item_id', sa.Integer(), nullable=True))
#     op.add_column('final_measurements', sa.Column('measured_qty', sa.DECIMAL(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
#     op.add_column('final_measurements', sa.Column('certified_qty', sa.DECIMAL(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
#     op.add_column('final_measurements', sa.Column('rejected_qty', sa.DECIMAL(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
#     op.add_column('final_measurements', sa.Column('retention_amount', sa.DECIMAL(precision=18, scale=2), server_default=sa.text('0'), nullable=False))
#     op.add_column('final_measurements', sa.Column('status', sa.String(length=50), server_default='DRAFT', nullable=False))
#     op.create_index(op.f('ix_final_measurements_boq_item_id'), 'final_measurements', ['boq_item_id'], unique=False)
#     op.create_index(op.f('ix_final_measurements_task_id'), 'final_measurements', ['task_id'], unique=False)
#     op.create_foreign_key(None, 'final_measurements', 'boq_items', ['boq_item_id'], ['id'], ondelete='SET NULL')
#     op.create_foreign_key(None, 'final_measurements', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.add_column('ra_bills', sa.Column('measurement_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ra_bills_measurement_id'), 'ra_bills', ['measurement_id'], unique=False)
    op.create_foreign_key(None, 'ra_bills', 'final_measurements', ['measurement_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ra_bills', type_='foreignkey')
    op.drop_index(op.f('ix_ra_bills_measurement_id'), table_name='ra_bills')
    op.drop_column('ra_bills', 'measurement_id')
    op.drop_constraint(None, 'final_measurements', type_='foreignkey')
    op.drop_constraint(None, 'final_measurements', type_='foreignkey')
    op.drop_index(op.f('ix_final_measurements_task_id'), table_name='final_measurements')
    op.drop_index(op.f('ix_final_measurements_boq_item_id'), table_name='final_measurements')
    op.drop_column('final_measurements', 'status')
    op.drop_column('final_measurements', 'retention_amount')
    op.drop_column('final_measurements', 'rejected_qty')
    op.drop_column('final_measurements', 'certified_qty')
    op.drop_column('final_measurements', 'measured_qty')
    op.drop_column('final_measurements', 'boq_item_id')
    op.drop_column('final_measurements', 'task_id')
    # ### end Alembic commands ###

