"""add work update module

Revision ID: f4353e1a6acd
Revises: 1901a325b8fe
Create Date: 2026-07-19 14:44:17.287008
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4353e1a6acd'
down_revision = '1901a325b8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.create_table(
        "work_updates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("business_id", sa.String(length=50), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("activity_type_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("work_description", sa.Text(), nullable=False),
        sa.Column("before_remarks", sa.Text(), nullable=True),
        sa.Column("after_remarks", sa.Text(), nullable=True),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("total_hours", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("Draft", "Submitted", name="workupdatestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["activity_type_id"], ["activity_types.id"]),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "idx_work_updates_project_date",
        "work_updates",
        ["project_id", "work_date"],
        unique=False,
    )

    op.create_index(
        "idx_work_updates_status",
        "work_updates",
        ["status"],
        unique=False,
    )

    op.create_index(
        op.f("ix_work_updates_activity_type_id"),
        "work_updates",
        ["activity_type_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_work_updates_business_id"),
        "work_updates",
        ["business_id"],
        unique=True,
    )

    op.create_index(
        op.f("ix_work_updates_created_by_id"),
        "work_updates",
        ["created_by_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_work_updates_project_id"),
        "work_updates",
        ["project_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_work_updates_task_id"),
        "work_updates",
        ["task_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_work_updates_work_date"),
        "work_updates",
        ["work_date"],
        unique=False,
    )

    op.create_table(
        "work_update_images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("work_update_id", sa.Integer(), nullable=False),
        sa.Column(
            "image_type",
            sa.Enum("Before", "After", name="workupdateimagetype"),
            nullable=False,
        ),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_update_id"],
            ["work_updates.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_work_update_images_image_type"),
        "work_update_images",
        ["image_type"],
        unique=False,
    )

    op.create_index(
        op.f("ix_work_update_images_work_update_id"),
        "work_update_images",
        ["work_update_id"],
        unique=False,
    )

def downgrade():
    op.drop_table("work_update_images")
    op.drop_table("work_updates")
    