"""Add actual dates to Task and Milestone

Revision ID: f5ec32624af9
Revises: 53b5a3e658fd
Create Date: 2026-06-02 14:15:51.493785
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ec32624af9'
down_revision = '53b5a3e658fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('actual_start_date', sa.Date(), nullable=True))
    op.add_column('milestones', sa.Column('actual_end_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('actual_start_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('actual_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'actual_end_date')
    op.drop_column('tasks', 'actual_start_date')
    op.drop_column('milestones', 'actual_end_date')
    op.drop_column('milestones', 'actual_start_date')
    # ### end Alembic commands ###

