"""trialsnewss

Revision ID: f8f25a2f7400
Revises: 862cca9c9d25
Create Date: 2026-05-26 14:25:44.316734
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8f25a2f7400'
down_revision = '862cca9c9d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_members',sa.Column('is_muted',sa.Boolean(),nullable=False,server_default=sa.false()))
    op.add_column('chat_members',sa.Column('is_archived',sa.Boolean(),nullable=False,server_default=sa.false()))
    op.add_column('chat_members', sa.Column('last_read_message_id', sa.Integer(), nullable=True))
    op.add_column('chat_members', sa.Column('last_read_at', sa.DateTime(), nullable=True))
    op.create_index('idx_member_last_read', 'chat_members', ['last_read_message_id'], unique=False)
    op.create_unique_constraint('uq_chat_user', 'chat_members', ['chat_id', 'user_id'])
    op.drop_constraint(op.f('chat_members_ibfk_1'), 'chat_members', type_='foreignkey')
    op.create_foreign_key(None, 'chat_members', 'chat_messages', ['last_read_message_id'], ['id'])
    op.create_foreign_key(None, 'chat_members', 'chat_sessions', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chat_messages_ibfk_1'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_chat_last_message', 'chat_sessions', ['last_message_at'], unique=False)
    op.add_column('chat_sessions', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('chat_messages',sa.Column('is_forwarded',sa.Boolean(),nullable=False,server_default=sa.false()))
    op.add_column('chat_messages', sa.Column('forwarded_from_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'chat_messages', ['forwarded_from_message_id'], ['id'])
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('created_at',sa.DateTime(),nullable=False,server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attachment_message', 'message_attachments', ['message_id'], unique=False)
    op.drop_column('chat_messages', 'attachment_url')
    op.alter_column('message_reactions', 'reaction',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_reactions', 'reaction',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.add_column('chat_messages', sa.Column('attachment_url', mysql.VARCHAR(length=500), nullable=True))
    op.drop_index('idx_attachment_message', table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'forwarded_from_message_id')
    op.drop_column('chat_messages', 'is_forwarded')
    op.drop_column('chat_sessions', 'avatar_url')
    op.drop_index('idx_chat_last_message', table_name='chat_sessions')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_ibfk_1'), 'chat_messages', 'chat_sessions', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.create_foreign_key(op.f('chat_members_ibfk_1'), 'chat_members', 'chat_sessions', ['chat_id'], ['id'])
    op.drop_constraint('uq_chat_user', 'chat_members', type_='unique')
    op.drop_index('idx_member_last_read', table_name='chat_members')
    op.drop_column('chat_members', 'last_read_at')
    op.drop_column('chat_members', 'last_read_message_id')
    op.drop_column('chat_members', 'is_archived')
    op.drop_column('chat_members', 'is_muted')
    # ### end Alembic commands ###

